const EN = {
  brand: "Haven",
  headerAria: "Haven",
  settingsAria: "Settings",
  helpAria: "Help & support",
  statusSignedIn: "Account: Signed in",
  statusSignedOut: "Account: Not signed in",
  statusRingBound: "Ring: Linked",
  statusRingNotBound: "Ring: Not linked",
  statusSealRingRecommended: "Seal: Ring enabled",
  statusSealSecureOnly: "Seal: Save Securely",
  tabTimeline: "Memories",
  tabExplore: "Explore",
  tabSeal: "Seal new",
  tabRings: "Rings",
  bottomNavAria: "Main",
  temporaryBanner:
    "Temporary device mode is on. This phone will wipe local memories and sign-in data when you leave.",
  /** Kept for backward route labels */
  breadcrumbAria: "Breadcrumb",
  home: "Home",
  timeline: "Timeline",
  settings: "Settings",
  help: "Help",
  new: "New",
  detail: "Detail",
};

export const APP_CHROME_CONTENT = {
  en: EN,
  fr: {
    ...EN,
    tabTimeline: "Souvenirs",
    tabExplore: "Explorer",
    tabSeal: "Sceller",
    tabRings: "Bagues",
    settingsAria: "Reglages",
    helpAria: "Aide",
  },
  es: {
    ...EN,
    tabTimeline: "Recuerdos",
    tabExplore: "Explorar",
    tabSeal: "Sellar",
    tabRings: "Anillos",
    settingsAria: "Configuracion",
    helpAria: "Ayuda",
  },
  de: {
    ...EN,
    tabTimeline: "Erinnerungen",
    tabExplore: "Entdecken",
    tabSeal: "Versiegeln",
    tabRings: "Ringe",
    settingsAria: "Einstellungen",
    helpAria: "Hilfe",
  },
  it: {
    ...EN,
    tabTimeline: "Ricordi",
    tabExplore: "Esplora",
    tabSeal: "Sigilla",
    tabRings: "Anelli",
    settingsAria: "Impostazioni",
    helpAria: "Aiuto",
  },
};
