export const BIND_RING_PAGE_EN = {
  kicker: "Bind ring",
  signInFailed: "Sign-in could not start. Please try again.",
  signInRequired: "Sign in to continue.",
  verifyDeviceFirst: "Verify this device first.",
  bindFailed: "Could not bind this ring. Please try again.",
  alreadyBound: "This ring is already bound.",
  statusUnlinked: "Ready to bind",
  statusCheckFailed: "Could not check ring status",
  signInRequiredShort: "Sign in required",
  openingSignIn: "Opening…",
  signInApple: "Sign in with Apple",
  signInGoogle: "Sign in with Google",
  nicknameLabel: "Nickname",
  devicePasswordLabel: "Device password",
  recoveryCodeLabel: "Recovery code",
  recoveryOptional: "Optional",
  binding: "Binding…",
} as const;
