export const FIRST_TIME_ONBOARDING_CONTENT = {
  en: {
    title: "Welcome to Haven",
    stepLabelPrefix: "Step ",
    stepLabelMiddle: " of ",
    subtitle: "A gentle start to your memory sanctuary.",
    layeredCoreLine:
      "Your Face ID protects your account. Your ring gives you fast access and a special ritual for your most precious memories.",
    skip: "Skip for now",
    next: "Next",
    back: "Back",
    start: "Start Using Now",
    openNfcGuide: "Learn about Rings",
    platformHintIos:
      "On iPhone, open Haven from the Home Screen icon for the smoothest daily experience.",
    platformHintAndroid:
      "On Android, you can continue directly in browser and use NFC ring touch more reliably.",
    steps: [
      {
        id: "welcome",
        illustration: "welcome",
        title: "Welcome to Haven",
        body: "Your private sanctuary for life’s most precious memories.",
        subtitle: "Safe. Beautiful. Yours.",
        primaryButton: "Begin Journey",
      },
      {
        id: "guardian",
        illustration: "guardian",
        title: "Your Face ID is the Guardian",
        body: "Every account is protected by the strongest biometric security. We never see your memories.",
        primaryButton: "Continue",
      },
      {
        id: "ring-key",
        illustration: "ring-key",
        title: "The Ring is Your Magical Key",
        body: "One touch for instant access. A sacred ritual for your most important memories.",
        subtitle: "Not just hardware — it’s part of the ceremony.",
        primaryButton: "Learn about Rings",
        action: "open-ring-guide",
      },
      {
        id: "memory-place",
        illustration: "draft-vs-seal",
        title: "Every Memory Has Its Place",
        body: "Quick thoughts go to Drafts.\nDeeply important moments deserve to be Sealed with the Ring.",
        primaryButton: "Continue",
      },
      {
        id: "ownership",
        illustration: "ownership",
        title: "Your Memories Belong Only to You",
        body: "End-to-end encrypted.\nYou control everything — including the power to revoke or delete anytime.",
        primaryButton: "Enter Haven",
      },
    ],
  },
  fr: {
    title: "Bienvenue sur Haven",
    subtitle: "Un debut doux pour votre sanctuaire de souvenirs.",
    skip: "Passer pour l'instant",
    next: "Suivant",
    back: "Retour",
    start: "Commencer maintenant",
    openNfcGuide: "En savoir plus sur les bagues",
    steps: [
      { id: "welcome", illustration: "welcome", title: "Bienvenue sur Haven", body: "Votre sanctuaire prive pour les souvenirs les plus precieux de la vie.", subtitle: "Securise. Beau. A vous.", primaryButton: "Commencer le voyage" },
      { id: "guardian", illustration: "guardian", title: "Votre Face ID est le Gardien", body: "Chaque compte est protege par une securite biometrique de haut niveau. Nous ne voyons jamais vos souvenirs." },
      { id: "ring-key", illustration: "ring-key", title: "La Bague est votre Cle magique", body: "Un toucher pour un acces instantane. Un rituel sacre pour vos souvenirs les plus importants.", subtitle: "Pas seulement du materiel — c'est une partie de la ceremonie.", primaryButton: "En savoir plus sur les bagues", action: "open-ring-guide" },
      { id: "memory-place", illustration: "draft-vs-seal", title: "Chaque souvenir a sa place", body: "Les pensees rapides vont dans les brouillons.\nLes moments profonds meritent d'etre scelles avec la bague." },
      { id: "ownership", illustration: "ownership", title: "Vos souvenirs n'appartiennent qu'a vous", body: "Chiffres de bout en bout.\nVous gardez le controle total — y compris revoquer ou supprimer a tout moment.", primaryButton: "Entrer dans Haven" },
    ],
  },
  es: {
    title: "Bienvenido a Haven",
    subtitle: "Un inicio suave para tu santuario de recuerdos.",
    skip: "Saltar por ahora",
    next: "Siguiente",
    back: "Atrás",
    start: "Empezar ahora",
    openNfcGuide: "Conoce los anillos",
    steps: [
      { id: "welcome", illustration: "welcome", title: "Bienvenido a Haven", body: "Tu santuario privado para los recuerdos mas valiosos de la vida.", subtitle: "Seguro. Bello. Tuyo.", primaryButton: "Comenzar viaje" },
      { id: "guardian", illustration: "guardian", title: "Tu Face ID es el Guardian", body: "Cada cuenta esta protegida con seguridad biometrica de alto nivel. Nunca vemos tus recuerdos." },
      { id: "ring-key", illustration: "ring-key", title: "El Anillo es tu Llave magica", body: "Un toque para acceso instantaneo. Un ritual sagrado para tus recuerdos mas importantes.", subtitle: "No es solo hardware — es parte de la ceremonia.", primaryButton: "Conoce los anillos", action: "open-ring-guide" },
      { id: "memory-place", illustration: "draft-vs-seal", title: "Cada recuerdo tiene su lugar", body: "Los pensamientos rapidos van a borradores.\nLos momentos profundos merecen sellarse con el anillo." },
      { id: "ownership", illustration: "ownership", title: "Tus recuerdos solo te pertenecen a ti", body: "Cifrado de extremo a extremo.\nTu controlas todo — incluido revocar o borrar en cualquier momento.", primaryButton: "Entrar a Haven" },
    ],
  },
  de: {
    title: "Willkommen bei Haven",
    subtitle: "Ein sanfter Start in dein Erinnerungsheiligtum.",
    skip: "Jetzt überspringen",
    next: "Weiter",
    back: "Zurück",
    start: "Jetzt starten",
    openNfcGuide: "Mehr uber Ringe",
    steps: [
      { id: "welcome", illustration: "welcome", title: "Willkommen bei Haven", body: "Dein privates Heiligtum fur die wertvollsten Erinnerungen deines Lebens.", subtitle: "Sicher. Schon. Deins.", primaryButton: "Reise beginnen" },
      { id: "guardian", illustration: "guardian", title: "Dein Face ID ist der Wachter", body: "Jedes Konto ist durch starke biometrische Sicherheit geschutzt. Wir sehen deine Erinnerungen nie." },
      { id: "ring-key", illustration: "ring-key", title: "Der Ring ist dein magischer Schlussel", body: "Eine Beruhrung fur sofortigen Zugriff. Ein heiliges Ritual fur deine wichtigsten Erinnerungen.", subtitle: "Nicht nur Hardware — sondern Teil der Zeremonie.", primaryButton: "Mehr uber Ringe", action: "open-ring-guide" },
      { id: "memory-place", illustration: "draft-vs-seal", title: "Jede Erinnerung hat ihren Platz", body: "Schnelle Gedanken gehen in Entwurfe.\nWichtige Momente verdienen es, mit dem Ring versiegelt zu werden." },
      { id: "ownership", illustration: "ownership", title: "Deine Erinnerungen gehoren nur dir", body: "Ende-zu-Ende verschlusselt.\nDu kontrollierst alles — auch Widerruf oder Loschen jederzeit.", primaryButton: "Haven betreten" },
    ],
  },
  it: {
    title: "Benvenuto in Haven",
    subtitle: "Un inizio dolce per il tuo santuario dei ricordi.",
    skip: "Salta per ora",
    next: "Avanti",
    back: "Indietro",
    start: "Inizia ora",
    openNfcGuide: "Scopri gli anelli",
    steps: [
      { id: "welcome", illustration: "welcome", title: "Benvenuto in Haven", body: "Il tuo santuario privato per i ricordi piu preziosi della vita.", subtitle: "Sicuro. Bellissimo. Tuo.", primaryButton: "Inizia il viaggio" },
      { id: "guardian", illustration: "guardian", title: "Il tuo Face ID e il Custode", body: "Ogni account e protetto dalla sicurezza biometrica piu forte. Non vediamo mai i tuoi ricordi." },
      { id: "ring-key", illustration: "ring-key", title: "L'Anello e la tua Chiave magica", body: "Un tocco per accesso istantaneo. Un rituale sacro per i tuoi ricordi piu importanti.", subtitle: "Non e solo hardware — e parte della cerimonia.", primaryButton: "Scopri gli anelli", action: "open-ring-guide" },
      { id: "memory-place", illustration: "draft-vs-seal", title: "Ogni ricordo ha il suo posto", body: "I pensieri rapidi vanno nelle bozze.\nI momenti profondi meritano di essere sigillati con l'anello." },
      { id: "ownership", illustration: "ownership", title: "I tuoi ricordi appartengono solo a te", body: "Cifratura end-to-end.\nHai il pieno controllo — inclusa la revoca o l'eliminazione in qualsiasi momento.", primaryButton: "Entra in Haven" },
    ],
  },
};
