export const FIRST_TIME_ONBOARDING_CONTENT = {
  en: {
    title: "Welcome to Haven Ring",
    stepLabelPrefix: "Step ",
    stepLabelMiddle: " of ",
    subtitle: "A gentle guide to your first moment.",
    skip: "Skip for now",
    next: "Next",
    back: "Back",
    start: "Start Using Now",
    openNfcGuide: "See ring position guide",
    steps: [
      { id: "welcome", icon: "💛", title: "Your ring is the key to your memories", body: "Think of your ring like a tiny door key. It opens your private Haven anytime." },
      { id: "entry-url", icon: "🔗", title: "Set one fixed entry once", body: "For first setup, write one fixed Haven entry on your ring. After that, no rewrite for each memory." },
      { id: "create-first", icon: "✍️", title: "Create your first memory", body: "Add photos, a short story, and optional files (audio, video, documents). Tap Save to keep it in your local Haven." },
      { id: "daily", icon: "✨", title: "Daily use is simple", body: "Just lightly tap your ring to open Haven and revisit your moments with one touch." },
    ],
  },
  fr: {
    title: "Bienvenue dans Haven Ring",
    subtitle: "Un guide simple pour votre premier moment.",
    skip: "Passer pour l'instant",
    next: "Suivant",
    back: "Retour",
    start: "Commencer maintenant",
    openNfcGuide: "Voir la position de la bague",
    steps: [
      { id: "welcome", icon: "💛", title: "Votre bague est la clé de vos souvenirs", body: "Considérez votre bague comme une petite clé. Elle ouvre votre Haven privé à tout moment." },
      { id: "entry-url", icon: "🔗", title: "Configurez une entrée fixe une seule fois", body: "Lors de la première configuration, écrivez une seule entrée Haven fixe sur la bague. Ensuite, aucune réécriture à chaque souvenir." },
      { id: "create-first", icon: "✍️", title: "Créez votre premier souvenir", body: "Ajoutez des photos, une histoire courte et une voix si vous voulez. Appuyez sur Enregistrer pour le garder dans votre Haven local." },
      { id: "daily", icon: "✨", title: "L'usage quotidien est simple", body: "Touchez légèrement la bague pour ouvrir Haven et revivre vos moments en un geste." },
    ],
  },
  es: {
    title: "Bienvenido a Haven Ring",
    subtitle: "Una guía simple para tu primer momento.",
    skip: "Saltar por ahora",
    next: "Siguiente",
    back: "Atrás",
    start: "Empezar ahora",
    openNfcGuide: "Ver guía de posición del anillo",
    steps: [
      { id: "welcome", icon: "💛", title: "Tu anillo es la llave de tus recuerdos", body: "Piensa en tu anillo como una pequeña llave. Abre tu Haven privado en cualquier momento." },
      { id: "entry-url", icon: "🔗", title: "Configura una entrada fija una vez", body: "En la primera configuración, escribe una entrada fija de Haven en el anillo. Después, no necesitas reescribirlo." },
      { id: "create-first", icon: "✍️", title: "Crea tu primer recuerdo", body: "Añade fotos, una historia corta y voz si quieres. Pulsa Guardar para conservarlo en tu Haven local." },
      { id: "daily", icon: "✨", title: "El uso diario es fácil", body: "Da un toque ligero con el anillo para abrir Haven y volver a tus recuerdos." },
    ],
  },
  de: {
    title: "Willkommen bei Haven Ring",
    subtitle: "Eine einfache Anleitung für den Start.",
    skip: "Jetzt überspringen",
    next: "Weiter",
    back: "Zurück",
    start: "Jetzt starten",
    openNfcGuide: "Ring-Position anzeigen",
    steps: [
      { id: "welcome", icon: "💛", title: "Dein Ring ist der Schlüssel zu deinen Erinnerungen", body: "Sieh deinen Ring als kleinen Schlüssel. Er öffnet dein privates Haven jederzeit." },
      { id: "entry-url", icon: "🔗", title: "Einmal festen Einstieg setzen", body: "Beim ersten Setup schreibst du einen festen Haven-Einstieg auf den Ring. Danach keine neue Schreibaktion pro Erinnerung." },
      { id: "create-first", icon: "✍️", title: "Erstelle deine erste Erinnerung", body: "Füge Fotos, eine kurze Geschichte und auf Wunsch Sprache hinzu. Mit Speichern bleibt alles in deinem lokalen Haven." },
      { id: "daily", icon: "✨", title: "Tägliche Nutzung ist leicht", body: "Tippe den Ring leicht an, um Haven zu öffnen und Momente wiederzusehen." },
    ],
  },
  it: {
    title: "Benvenuto in Haven Ring",
    subtitle: "Una guida semplice per iniziare.",
    skip: "Salta per ora",
    next: "Avanti",
    back: "Indietro",
    start: "Inizia ora",
    openNfcGuide: "Mostra guida posizione anello",
    steps: [
      { id: "welcome", icon: "💛", title: "Il tuo anello è la chiave dei tuoi ricordi", body: "Pensa all'anello come a una piccola chiave. Apre il tuo Haven privato in ogni momento." },
      { id: "entry-url", icon: "🔗", title: "Imposta un ingresso fisso una sola volta", body: "Alla prima configurazione scrivi un ingresso Haven fisso sull'anello. Poi non serve riscriverlo ogni volta." },
      { id: "create-first", icon: "✍️", title: "Crea il tuo primo ricordo", body: "Aggiungi foto, una breve storia e voce se vuoi. Premi Salva per conservarlo nel tuo Haven locale." },
      { id: "daily", icon: "✨", title: "Uso quotidiano semplice", body: "Un leggero tocco dell'anello basta per aprire Haven e rivivere i tuoi momenti." },
    ],
  },
};
