export const FIRST_TIME_ONBOARDING_CONTENT = {
  en: {
    title: "Welcome to Haven Ring",
    stepLabelPrefix: "Step ",
    stepLabelMiddle: " of ",
    subtitle: "Your first memory can be safe in just a few minutes.",
    layeredCoreLine:
      "Your Face ID protects your account. Your ring gives you fast access and a special ritual for your most precious memories.",
    skip: "Skip for now",
    next: "Next",
    back: "Back",
    start: "Start Using Now",
    openNfcGuide: "See ring position guide in Settings",
    howHavenWorksTitle: "How Haven Works",
    howHavenWorksIntro:
      "欢迎来到你的私人记忆圣殿。这里的一切都设计得简单且安全。",
    howHavenWorksPoints: [
      "日常打开应用：戒指不强制（强烈推荐），也可用 Face ID / Touch ID / Passkey。",
      "快速记录想法（草稿箱）：不需要戒指，登录后直接开始记录。",
      "重要记忆封印（Seal）：推荐 Seal with Ring；备选 Save Securely（Face ID）。",
      "高风险操作（加/解绑戒指、导出迁移、删除封印）：必须二次验证。",
    ],
    howHavenWorksOneLine:
      "一句话总结：“戒指为你提供速度与仪式感，Face ID 保护你的账号安全。”",
    platformHintIos:
      "On iPhone, open Haven from the Home Screen icon for the smoothest daily experience.",
    platformHintAndroid:
      "On Android, you can continue directly in browser and use NFC ring touch more reliably.",
    steps: [
      {
        id: "welcome",
        icon: "💛",
        title: "Your memories always belong to you",
        body: "Haven is your private memory sanctuary. Your signed-in account is the owner of every memory, now and in the future.",
      },
      {
        id: "create-first",
        icon: "✍️",
        title: "Start with one memory first",
        body: "Write a short story, add photos if you like, and save. You can do this immediately without learning NFC first.",
      },
      {
        id: "entry-url",
        icon: "💍",
        title: "Ring setup is recommended, not required",
        body: "Your NFC ring adds a beautiful quick-open and sealing ritual. If you are in a hurry, you can skip now and set it up later.",
      },
      {
        id: "daily",
        icon: "✨",
        title: "Daily use stays simple",
        body: "Open Haven, add memories, and seal when you want. For precious moments, use Seal with Ring as your ritual, or Save Securely with Face ID as smooth fallback.",
      },
    ],
  },
  fr: {
    title: "Bienvenue dans Haven Ring",
    subtitle: "Un guide simple pour votre premier moment.",
    skip: "Passer pour l'instant",
    next: "Suivant",
    back: "Retour",
    start: "Commencer maintenant",
    openNfcGuide: "Voir la position de la bague",
    steps: [
      { id: "welcome", icon: "💛", title: "Votre compte est la base ; la bague est un raccourci", body: "Haven repose sur votre compte connecte. La bague sert d'acces rapide pour ouvrir ou sceller — comme un favori, pas comme un mot de passe. Plusieurs bagues possibles, toutes egales." },
      { id: "entry-url", icon: "🔗", title: "Configurez une entrée fixe une seule fois", body: "Lors de la première configuration, écrivez une seule entrée Haven fixe sur la bague. Ensuite, aucune réécriture à chaque souvenir." },
      { id: "create-first", icon: "✍️", title: "Créez votre premier souvenir", body: "Ajoutez des photos, une histoire courte et une voix si vous voulez. Appuyez sur Enregistrer pour le garder dans votre Haven local." },
      { id: "daily", icon: "✨", title: "L'usage quotidien est simple", body: "Un leger toucher ouvre Haven. Toute bague liee a ce compte fonctionne pareil — pas de bague principale obligatoire." },
    ],
  },
  es: {
    title: "Bienvenido a Haven Ring",
    subtitle: "Una guía simple para tu primer momento.",
    skip: "Saltar por ahora",
    next: "Siguiente",
    back: "Atrás",
    start: "Empezar ahora",
    openNfcGuide: "Ver guía de posición del anillo",
    steps: [
      { id: "welcome", icon: "💛", title: "Tu cuenta es el hogar; el anillo es un atajo", body: "Haven pertenece a tu cuenta iniciada. El anillo es un toque rapido para abrir o sellar — como un acceso directo, no tu contrasena. Puedes usar varios anillos; todos valen igual." },
      { id: "entry-url", icon: "🔗", title: "Configura una entrada fija una vez", body: "En la primera configuración, escribe una entrada fija de Haven en el anillo. Después, no necesitas reescribirlo." },
      { id: "create-first", icon: "✍️", title: "Crea tu primer recuerdo", body: "Añade fotos, una historia corta y voz si quieres. Pulsa Guardar para conservarlo en tu Haven local." },
      { id: "daily", icon: "✨", title: "El uso diario es fácil", body: "Un toque ligero abre Haven. Cualquier anillo vinculado a esta cuenta funciona igual — no hace falta un anillo principal." },
    ],
  },
  de: {
    title: "Willkommen bei Haven Ring",
    subtitle: "Eine einfache Anleitung für den Start.",
    skip: "Jetzt überspringen",
    next: "Weiter",
    back: "Zurück",
    start: "Jetzt starten",
    openNfcGuide: "Ring-Position anzeigen",
    steps: [
      { id: "welcome", icon: "💛", title: "Dein Konto ist die Basis; der Ring ist ein Kurzbefehl", body: "Haven gehort zu deinem angemeldeten Konto. Der Ring offnet oder versiegelt schnell — wie eine Verknupfung, nicht dein Passwort. Mehrere Ringe sind gleichwertig moglich." },
      { id: "entry-url", icon: "🔗", title: "Einmal festen Einstieg setzen", body: "Beim ersten Setup schreibst du einen festen Haven-Einstieg auf den Ring. Danach keine neue Schreibaktion pro Erinnerung." },
      { id: "create-first", icon: "✍️", title: "Erstelle deine erste Erinnerung", body: "Füge Fotos, eine kurze Geschichte und auf Wunsch Sprache hinzu. Mit Speichern bleibt alles in deinem lokalen Haven." },
      { id: "daily", icon: "✨", title: "Tägliche Nutzung ist leicht", body: "Ein leichter Tipp offnet Haven. Jeder mit diesem Konto verknupfte Ring funktioniert gleich — kein Pflicht-Haupt-Ring." },
    ],
  },
  it: {
    title: "Benvenuto in Haven Ring",
    subtitle: "Una guida semplice per iniziare.",
    skip: "Salta per ora",
    next: "Avanti",
    back: "Indietro",
    start: "Inizia ora",
    openNfcGuide: "Mostra guida posizione anello",
    steps: [
      { id: "welcome", icon: "💛", title: "Il tuo account e la base; l'anello e una scorciatoia", body: "Haven appartiene al tuo account. L'anello serve per aprire o sigillare in fretta — come un collegamento, non la password. Puoi avere piu anelli, tutti equivalenti." },
      { id: "entry-url", icon: "🔗", title: "Imposta un ingresso fisso una sola volta", body: "Alla prima configurazione scrivi un ingresso Haven fisso sull'anello. Poi non serve riscriverlo ogni volta." },
      { id: "create-first", icon: "✍️", title: "Crea il tuo primo ricordo", body: "Aggiungi foto, una breve storia e voce se vuoi. Premi Salva per conservarlo nel tuo Haven locale." },
      { id: "daily", icon: "✨", title: "Uso quotidiano semplice", body: "Un leggero tocco apre Haven. Ogni anello collegato a questo account funziona allo stesso modo — nessun anello principale obbligatorio." },
    ],
  },
};
