const EN = {
  navComposerTitle: "New memory",
  topBarSealing: "Sealing…",
  heroSealTitle: "Seal this moment",
  heroSealSubtitleIos:
    "Mark this moment with a ring ritual — a lasting, intentional way to keep this memory.",
  heroSealSubtitleAndroid: "Seal this memory fast with your ring — one touch completes it.",
  heroSealSubtitleOther: "Confirm this memory with your Haven ring when you're ready.",
  sealPrimaryHintIos: "Touch your Haven ring to the top of your iPhone when you're ready.",
  sealPrimaryHintAndroid: "Touch your Haven ring to the NFC area on the back of your phone.",
  sealPrimaryHintOther: "Use your phone's NFC with your Haven ring to confirm.",
  saveSecureLinkIos: "Or save securely with Face ID",
  saveSecureLinkAndroid: "Or save securely with fingerprint / screen lock",
  saveSecureLinkOther: "Or save securely to this device",
  sealPrimaryShort: "Seal with Ring",
  editorSectionTitle: "Your story & media",
  storyCharCount: "{n} characters",
  storyCharSoftMaxWarn: "Very long text may slow saving on older phones.",
  footerNeedDraft: "Save a draft first — then you can seal with your ring.",
  footerSealInvite: "Tap Seal with Ring above to save and prepare — then touch your ring.",
  footerReadySealIos: "Lift your ring and hold it near your iPhone to complete the ritual.",
  footerReadySealAndroid: "Ring is ready — one light touch finishes it.",
  footerReadySeal: "Ready — touch your ring to seal when your phone prompts you.",
  footerSaving: "Saving…",
  footerWaitingRingIos: "Waiting for your ring — hold it to the top of your iPhone.",
  footerWaitingRingAndroid: "Waiting for your ring — keep it steady near the NFC spot.",
  footerWaitingRing: "Waiting for your ring — follow the on-screen NFC steps.",
  footerOfflineSeal:
    "You need an internet connection to finish sealing after the ring touch. Stay online or try again when you're back.",
  sealPrimaryCtaReady: "Touch ring to seal",
  sealPrimaryCtaWaiting: "Waiting for ring touch…",
  sealWaitingBannerTitle: "Waiting for your ring",
  sealWaitingBannerBodyIos:
    "Bring your Haven ring close to your iPhone. Add Haven to your Home Screen first for the most reliable NFC handoff.",
  sealWaitingBannerBodyAndroid:
    "Hold your Haven ring near the back of your phone. You should feel a quick system prompt when NFC reads the ring.",
  sealWaitingBannerBodyOther: "Hold your Haven ring near your device's NFC reader until this step completes.",
  cancelSealFlow: "Cancel this seal",
  sealCountdownPrefix: "Time left to touch:",
  sealArmExpired: "Seal wait timed out. Tap Seal with Ring again when you're ready.",
  secureSaveToast:
    "Saved securely on this device. You can come back any time and seal this memory with your ring.",
  sealAfterSecureSaveCta: "Seal this memory now",
  securityDeleteNoteIos:
    "Sealed memories need Face ID plus an extra confirmation before they can be removed.",
  securityDeleteNoteAndroid:
    "Sealed memories need your screen lock plus an extra confirmation before they can be removed.",
  securityDeleteNoteOther:
    "Sealed memories need your device lock plus an extra confirmation before they can be removed.",
  storyRequiredHint: "Add a few words about this moment — it's required to seal.",
  upgradeModalTitle: "Unlock the Ritual Experience",
  upgradeModalBody:
    "Haven Plus unlocks Seal with Ring and optional cloud backup where we offer it — about 50 GB for Plus where available. Link your first ring to start a 30-day trial where available.",
  upgradeModalDismiss: "Maybe later",
  upgradeSealShort: "Haven Plus unlocks Seal with Ring.",
  upgradeSealCta: "30-day trial when you link your ring — upgrade anytime in Rings.",
  title: "Capture this moment",
  freePlanOneLiner:
    "Free plan: 2 GB local storage. Seal with Ring requires Haven Plus.",
  addPhotosCta: "Add Photos (max 6)",
  addVideoCta: "Add Videos (max 6)",
  addFilesCta: "Add Files (max 5)",
  mediaZoneAria: "Photos, videos, and files",
  mediaLimitsSummary:
    "Photos: up to 6 (compressed on your device). Videos: up to 6 clips, max 10 MB each (MP4, MOV, WebM). Files: up to 5 attachments, max 10 MB each — PDF, Word, Excel, PowerPoint, audio, zip.",
  photosSectionHeading: "Photos",
  videosSectionHeading: "Videos",
  filesSectionHeading: "Documents & audio",
  removePhotoAria: "Remove photo",
  removeVideoAria: "Remove video",
  videoAttachmentsLabel: "Videos",
  videoPreviewPending: "Preview…",
  feedbackWrongPickerVideosPrefix: "Use “Add Videos” for clips. Skipped: ",
  feedbackWrongPickerVideosSuffix: ".",
  feedbackSkippedVideoClips:
    "{n} clip(s) skipped — limit is {max} videos, {mb} MB each.",
  feedbackSkippedFileAttachments:
    "{n} file(s) skipped — limit is {max} documents or audio files, {mb} MB each.",
  optionalDetailsToggle: "Title & schedule (optional)",
  optionalDetailsHide: "Hide title & schedule",
  helpAriaLabel: "Help",
  iosComposeHint:
    "iPhone tip: open Haven from your Home Screen for the smoothest seal flow.",
  androidComposeHint:
    "Android: use Chrome or your Haven app from the Play Store; keep clips under 10 MB so saving stays quick.",
  helperLine: "Touch your trusted ring to begin the sacred ritual.",
  learnMore: "Learn more",
  modeQuickRecord: "Quick Record",
  modeSealMemory: "Seal Memory",
  sealModeHint: "Touch your trusted ring to begin the sacred ritual.",
  quickModeHint: "Quick Record saves fast drafts for daily thoughts.",
  back: "Back",
  titleLabel: "Title",
  titlePlaceholder: "A quiet title...",
  storyLabel: "Story",
  storyPlaceholder: "Write what this memory means to you...",
  timeCapsuleLabel: "Time capsule unlock time",
  timeCapsuleHint:
    "Optional. Before this time, memory content stays locked and hidden.",
  photosLabel: "Photos",
  choosePhotos: "Choose photos",
  noPhotosSelected: "No photos selected",
  photosSelectedSuffix: " selected",
  photosHint: "Select 1 or more photos (max 6). Auto-compressed on device.",
  photosCountPrefix: "(",
  photosCountSuffix: ")",
  attachmentsLabel: "Attachments",
  chooseAttachments: "Choose files",
  chooseVideo: "Choose video",
  noAttachmentsSelected: "No files selected",
  attachmentsSelectedSuffix: " file(s)",
  attachmentsHint:
    "Upload audio, video, or document files. Max 10 MB per file, up to 5 files.",
  removeAttachment: "Remove",
  saving: "Saving...",
  quickDraft: "Quick Draft",
  quickDraftHint: "Save instantly to your Draft Box.",
  sealFabHint: "Touch your trusted ring to begin the sacred ritual.",
  sealFabUpgradeHint: "Haven Plus unlocks the physical ring ritual.",
  upgradeSealWithRing:
    "Unlock Seal with Ring with Haven Plus — 30 days free with your ring. Free users can still Save Securely with Face ID.",
  planDualTrackHint:
    "Readable drafts stay in your local Draft Box until you seal. Seal with Ring adds the memory to your encrypted sanctuary timeline.",
  sealNeedsNetworkHint:
    "You need a network connection to finish sealing after the ring touch. Your draft stays on this device.",
  addDetails: "Add details",
  hideDetails: "Hide details",
  sealNow: "Seal with Ring — Make this memory sacred",
  sealNowOptionalIos: "Seal with Ring — Make this memory sacred",
  haptic: "Haptic feedback",
  sound: "Success sound",
  soundSaveOnly: "Sound only on save success",
  feedbackCompressing: "Compressing photos...",
  feedbackAddedPhotosPrefix: "Added ",
  feedbackAddedPhotosSuffix: " photo(s).",
  feedbackMaxPhotosPrefix: "Max ",
  feedbackMaxPhotosSuffix: " photos allowed.",
  feedbackPhotoError: "Could not process photos. Please try again.",
  feedbackAttachmentTooLargePrefix: "File too large: ",
  feedbackAttachmentTooLargeSuffix: ". Max size is 10 MB.",
  feedbackAttachmentTooLargeManyPrefix: "Skipped ",
  feedbackAttachmentTooLargeManyMiddle: " oversized file(s). Max ",
  feedbackAttachmentTooLargeManySuffix: " MB each. Example: ",
  feedbackAttachmentSlotsExceededPrefix: "Skipped ",
  feedbackAttachmentSlotsExceededSuffix: " file(s): attachment limit is ",
  feedbackAttachmentAddedPrefix: "Added ",
  feedbackAttachmentAddedSuffix: " file(s).",
  feedbackAttachmentError: "Could not process selected files. Please try again.",
  feedbackMaxAttachmentsPrefix: "Max ",
  feedbackMaxAttachmentsSuffix: " files allowed.",
  feedbackNeedContent: "Add your story or media, then save — sealing needs something to hold onto.",
  feedbackSavingLocal: "Saving draft locally...",
  feedbackSavingTimeline: "Encrypting and saving to your timeline...",
  feedbackSaved: "Draft saved. Touch your ring to seal.",
  feedbackSavedTimeline: "Saved to your timeline. You can open it from Home.",
  feedbackReadyToSeal: "Touch your trusted ring to begin the sacred ritual.",
  feedbackMissingVerifiedTap:
    "No verified ring tap was detected. Please touch your ring and return to complete sealing.",
  feedbackDraftRestored: "Recovered your unsaved draft.",
  feedbackSaveFailed: "Save failed.",
  feedbackReadyNext: "Ready for your next memory.",
  feedbackSealPrepNeedDraftSave:
    "Save this memory as a draft first — then use Seal with Ring from this screen.",
  untitled: "Untitled memory",
  canvasUnavailable: "Canvas not available.",
  compressionFailed: "Compression failed.",
  invalidImage: "Invalid image file.",
  readBinaryFailed: "Failed to read binary data.",
  memoryTypeTitle: "Choose memory type",
  memoryTypeText: "Text Memory",
  memoryTypePhotoVideo: "Photo / Video",
  memoryTypeVoice: "Voice Note",
  memoryTypeMixed: "Mixed Memory",
  sealPromptTitle: "Seal This Memory?",
  sealPromptRuleLine: "Touch your trusted ring to begin the sacred ritual.",
  sealPromptBody: "Waiting for your dynamic ring touch.",
  sealPromptIosHint:
    "On iPhone, open Haven from your Home Screen shortcut before touching the ring for a more reliable seal flow.",
  sealPromptDone: "I touched the ring",
  sealTouchInstruction:
    "Touch your ring to your phone to confirm identity and get a one-time seal ticket.",
  sealTouchRetry: "Seal with Ring — Make this memory sacred",
  sealTouchWorking: "Reading ring...",
  sealTicketReady: "Ring verified. You can confirm sealing now.",
  sealConfirmButton: "Seal with Ring",
  sealStatusTitle: "Seal physical confirmation",
  sealStatusWaiting: "Touch your trusted ring to begin the sacred ritual.",
  sealStatusReading: "Reading your ring. Keep it still near your phone.",
  sealStatusVerified: "Trusted ring verified. Finishing the seal now.",
  sealSuccessWarm: "Your memory is now sealed, safe, and ready to keep.",
  sealNeedSignIn: "Please sign in again before sealing this memory.",
  sealRingReadFailed:
    "Ring touch did not complete. Please touch again with a trusted ring to continue sealing.",
  sealCommitRetryHint:
    "Your memory is safe. Final sealing is still finishing—please retry confirm in a moment.",
  sealFallbackTitle: "Touch did not work?",
  sealFallbackBody:
    "Seal requires a trusted ring. Save this as a draft and seal it later when your ring is with you.",
  sealFallbackPassword: "Device password",
  sealFallbackRecovery: "Or recovery code",
  sealFallbackAction: "Save as Draft",
  sealSecureQuickAction: "Save Securely with Face ID",
  sealFallbackWorking: "Saving draft...",
  sealPromptClose: "Close",
  sealWithFaceId: "Save Draft",
  errInvalidTicket: "Please touch your ring again to confirm your identity.",
  errTicketExpired: "That confirmation timed out. Please try Seal with Ring again.",
  errTicketUsed: "This confirmation was already used. Please touch your ring again.",
  errInvalidRingTouch: "We could not read your ring clearly. Please try touching again.",
  errRingNotLinked: "This ring is not linked yet. Please use one of your linked rings.",
  errRateLimited: "You are moving a little fast. Please wait a moment and try again.",
  errNeedSignIn: "Please sign in again, then continue sealing your memory.",
  errGenericWarmFallback:
    "Something small went wrong. Please try your trusted ring again, or save as a draft.",
  backlogTitle: "Planned enhancements (backlog)",
  backlogTimeCapsule: "Advanced time capsule rules (for example recurring unlock plans).",
  backlogTags: "Richer tag editor (multi-tag suggestions and quick chips).",
  backlogGeo: "Optional location marker with explicit permission flow.",
  draftBoxTitle: "Draft box",
  draftBoxShow: "Show draft box",
  draftBoxHide: "Hide draft box",
  draftBoxEmpty: "No saved drafts yet.",
  draftSealSelected: "Seal selected drafts ({n})",
  draftEdit: "Edit",
  draftSealNow: "Seal now",
  undoSealAction: "Undo",
  feedbackUndoWindow:
    "Preparing to seal {n} draft(s). You can undo for a few seconds.",
  feedbackUndoDone: "Seal action was undone. Drafts are still in your box.",
};

export const NEW_MEMORY_PAGE_CONTENT = {
  en: EN,
  fr: { ...EN, title: "Capturez ce moment", helperLine: "Touchez votre bague pour sceller ce souvenir.", sealModeHint: "Touchez votre bague pour sceller ce souvenir.", sealFabHint: "Touchez votre bague pour sceller ce souvenir.", sealSecureQuickAction: "Enregistrer securise avec Face ID", sealStatusTitle: "Confirmation physique du scellement", sealStatusWaiting: "Touchez une bague de confiance pour confirmer physiquement ce souvenir sacre.", sealStatusReading: "Lecture de votre bague. Gardez-la immobile pres du telephone.", sealStatusVerified: "Bague de confiance verifiee. Le scellement se termine maintenant.", sealPromptRuleLine: "Seules les bagues de confiance peuvent sceller les souvenirs sacres.", back: "Retour", titleLabel: "Titre", storyLabel: "Histoire", photosLabel: "Photos", choosePhotos: "Choisir des photos", noPhotosSelected: "Aucune photo selectionnee", photosSelectedSuffix: " selectionnees" },
  es: { ...EN, title: "Captura este momento", helperLine: "Toca tu anillo para sellar este recuerdo.", sealModeHint: "Toca tu anillo para sellar este recuerdo.", sealFabHint: "Toca tu anillo para sellar este recuerdo.", sealSecureQuickAction: "Guardar de forma segura con Face ID", sealStatusTitle: "Confirmacion fisica del sello", sealStatusWaiting: "Toca un anillo de confianza para confirmar fisicamente este recuerdo sagrado.", sealStatusReading: "Leyendo tu anillo. Mantenlo quieto cerca del telefono.", sealStatusVerified: "Anillo de confianza verificado. Terminando el sello ahora.", sealPromptRuleLine: "Solo los anillos de confianza pueden sellar recuerdos sagrados.", back: "Volver", titleLabel: "Titulo", storyLabel: "Historia", photosLabel: "Fotos", choosePhotos: "Elegir fotos", noPhotosSelected: "Ninguna foto seleccionada", photosSelectedSuffix: " seleccionadas" },
  de: { ...EN, title: "Halte diesen Moment fest", helperLine: "Berühre deinen Ring, um diese Erinnerung zu versiegeln.", sealModeHint: "Berühre deinen Ring, um diese Erinnerung zu versiegeln.", sealFabHint: "Berühre deinen Ring, um diese Erinnerung zu versiegeln.", sealSecureQuickAction: "Sicher mit Face ID speichern", sealStatusTitle: "Physische Versiegelungsbestätigung", sealStatusWaiting: "Berühre einen vertrauenswürdigen Ring, um diese heilige Erinnerung physisch zu bestätigen.", sealStatusReading: "Dein Ring wird gelesen. Halte ihn ruhig nahe ans Telefon.", sealStatusVerified: "Vertrauenswürdiger Ring bestätigt. Die Versiegelung wird abgeschlossen.", sealPromptRuleLine: "Nur vertrauenswurdige Ringe konnen heilige Erinnerungen versiegeln.", back: "Zuruck", titleLabel: "Titel", storyLabel: "Geschichte", photosLabel: "Fotos", choosePhotos: "Fotos auswahlen", noPhotosSelected: "Keine Fotos ausgewahlt", photosSelectedSuffix: " ausgewahlt" },
  it: { ...EN, title: "Cattura questo momento", helperLine: "Tocca l'anello per sigillare questo ricordo.", sealModeHint: "Tocca l'anello per sigillare questo ricordo.", sealFabHint: "Tocca l'anello per sigillare questo ricordo.", sealSecureQuickAction: "Salva in modo sicuro con Face ID", sealStatusTitle: "Conferma fisica del sigillo", sealStatusWaiting: "Tocca un anello fidato per confermare fisicamente questo ricordo sacro.", sealStatusReading: "Lettura dell'anello. Tienilo fermo vicino al telefono.", sealStatusVerified: "Anello fidato verificato. Il sigillo si sta completando.", sealPromptRuleLine: "Solo gli anelli fidati possono sigillare ricordi sacri.", back: "Indietro", titleLabel: "Titolo", storyLabel: "Storia", photosLabel: "Foto", choosePhotos: "Scegli foto", noPhotosSelected: "Nessuna foto selezionata", photosSelectedSuffix: " selezionate" },
};
