const EN = {
  brand: "New Memory",
  title: "Capture this moment",
  sealGuidance:
    "Do not tap your ring while editing. Tap only after pressing Seal with Ring Now.",
  layeredCoreLine:
    "Your Face ID protects your account. Your ring gives you fast access and a special ritual for your most precious memories.",
  sealGuidanceIos:
    "On iPhone, Save Securely is the smooth default. Seal with Ring remains available as an optional ritual.",
  sealGuidanceAndroid:
    "On Android, Seal with Ring works well for daily ritual use. Save Securely stays available anytime.",
  statusCardTitle: "Your current status",
  statusSignedIn: "Signed in to account",
  statusSignedOut: "Not signed in yet",
  statusRingLinked: "Ring linked to this account",
  statusRingNotLinked: "No ring linked yet",
  statusSealRuleWithRing:
    "For precious memories: Ring is recommended for the ritual. Save Securely still works anytime.",
  statusSealRuleNoRing:
    "Ring touch is not required. You can always finish with Save Securely with Face ID.",
  firstMemoryQuickTitle: "Your first memory can be simple",
  firstMemoryQuickBody:
    "Start with a short title and one sentence. You can add files and advanced options later.",
  firstMemoryShowAdvanced: "Add optional details",
  firstMemoryAddFiles: "Add files (optional)",
  firstMemoryAddVideo: "Add video (optional)",
  back: "Back",
  titleLabel: "Title",
  titlePlaceholder: "A quiet title...",
  storyLabel: "Story",
  storyPlaceholder: "Write what this memory means to you...",
  timeCapsuleLabel: "Time capsule unlock time",
  timeCapsuleHint:
    "Optional. Before this time, memory content stays locked and hidden.",
  photosLabel: "Photos",
  choosePhotos: "Choose photos",
  noPhotosSelected: "No photos selected",
  photosSelectedSuffix: " selected",
  photosHint: "Select 1 or more photos (max 6). Auto-compressed on device.",
  photosCountPrefix: "(",
  photosCountSuffix: ")",
  attachmentsLabel: "Attachments",
  chooseAttachments: "Choose files",
  chooseVideo: "Choose video",
  noAttachmentsSelected: "No files selected",
  attachmentsSelectedSuffix: " file(s)",
  attachmentsHint:
    "Upload audio, video, or document files. Max 10 MB per file, up to 5 files.",
  removeAttachment: "Remove",
  saving: "Saving...",
  save: "Save Draft",
  sealNow: "Seal with Ring — Make this memory sacred",
  sealNowOptionalIos: "Seal with Ring — Make this memory sacred",
  haptic: "Haptic feedback",
  sound: "Success sound",
  soundSaveOnly: "Sound only on save success",
  privacyHint:
    "Saving creates a local draft only. Final seal requires touching your ring.",
  feedbackCompressing: "Compressing photos...",
  feedbackAddedPhotosPrefix: "Added ",
  feedbackAddedPhotosSuffix: " photo(s).",
  feedbackMaxPhotosPrefix: "Max ",
  feedbackMaxPhotosSuffix: " photos allowed.",
  feedbackPhotoError: "Could not process photos. Please try again.",
  feedbackAttachmentTooLargePrefix: "File too large: ",
  feedbackAttachmentTooLargeSuffix: ". Max size is 10 MB.",
  feedbackAttachmentAddedPrefix: "Added ",
  feedbackAttachmentAddedSuffix: " file(s).",
  feedbackAttachmentError: "Could not process selected files. Please try again.",
  feedbackMaxAttachmentsPrefix: "Max ",
  feedbackMaxAttachmentsSuffix: " files allowed.",
  feedbackNeedContent: "Add some memory content before saving.",
  feedbackSavingLocal: "Saving draft locally...",
  feedbackSaved: "Draft saved. Touch your ring to seal.",
  feedbackReadyToSeal: "Ready to seal. Touch your ring now.",
  feedbackMissingVerifiedTap:
    "No verified ring tap was detected. Please touch your ring and return to complete sealing.",
  feedbackDraftRestored: "Recovered your unsaved draft.",
  feedbackSaveFailed: "Save failed.",
  feedbackReadyNext: "Ready for your next memory.",
  untitled: "Untitled memory",
  canvasUnavailable: "Canvas not available.",
  compressionFailed: "Compression failed.",
  invalidImage: "Invalid image file.",
  readBinaryFailed: "Failed to read binary data.",
  sealPromptTitle: "Final step: touch your ring",
  sealPromptBody:
    "Take a calm breath, then hold your ring near the back of your phone. Sealing finishes after a verified touch.",
  sealPromptIosHint:
    "On iPhone, open Haven from your Home Screen shortcut before touching the ring for a more reliable seal flow.",
  sealPromptDone: "I touched the ring",
  sealTouchInstruction:
    "Touch your ring to your phone to confirm identity and get a one-time seal ticket.",
  sealTouchRetry: "Seal with Ring — Make this memory sacred",
  sealTouchWorking: "Reading ring...",
  sealTicketReady: "Ring verified. You can confirm sealing now.",
  sealConfirmButton: "Confirm seal",
  sealSuccessWarm: "Your memory is now sealed, safe, and ready to keep.",
  sealNeedSignIn: "Please sign in again before sealing this memory.",
  sealRingReadFailed:
    "Ring touch did not complete. Try touching again, or use Save Securely below.",
  sealCommitRetryHint:
    "Your memory is safe. Final sealing is still finishing—please retry confirm in a moment.",
  sealFallbackTitle: "Touch did not work?",
  sealFallbackBody:
    "If ring touch is not convenient right now, you can still finish safely with device verification.",
  sealFallbackPassword: "Device password",
  sealFallbackRecovery: "Or recovery code",
  sealFallbackAction: "Save Securely with Face ID",
  sealSecureQuickAction: "Save Securely with Face ID",
  sealChoiceHintTitle: "How Haven Works",
  sealChoiceHintBody:
    "重要记忆推荐使用戒指封印（仪式路径），但并非强制。你也可以随时使用 Save Securely with Face ID。",
  sealFallbackWorking: "Saving securely...",
  sealPromptClose: "Close",
  errInvalidTicket: "Please touch your ring again to confirm your identity.",
  errTicketExpired: "That confirmation timed out. Please try Seal with Ring again.",
  errTicketUsed: "This confirmation was already used. Please touch your ring again.",
  errInvalidRingTouch: "We could not read your ring clearly. Please try touching again.",
  errRingNotLinked: "This ring is not linked yet. Please use one of your linked rings.",
  errRateLimited: "You are moving a little fast. Please wait a moment and try again.",
  errNeedSignIn: "Please sign in again, then continue sealing your memory.",
  errGenericWarmFallback:
    "Something small went wrong. Please try again shortly, or use Save Securely.",
  backlogTitle: "Planned enhancements (backlog)",
  backlogTimeCapsule: "Advanced time capsule rules (for example recurring unlock plans).",
  backlogTags: "Richer tag editor (multi-tag suggestions and quick chips).",
  backlogGeo: "Optional location marker with explicit permission flow.",
  draftBoxTitle: "Draft box",
  draftBoxEmpty: "No saved drafts yet.",
  draftSealSelected: "Seal selected drafts ({n})",
  draftEdit: "Edit",
  draftSealNow: "Seal now",
  undoSealAction: "Undo",
  feedbackUndoWindow:
    "Preparing to seal {n} draft(s). You can undo for a few seconds.",
  feedbackUndoDone: "Seal action was undone. Drafts are still in your box.",
};

export const NEW_MEMORY_PAGE_CONTENT = {
  en: EN,
  fr: { ...EN, brand: "Nouveau souvenir", title: "Capturez ce moment", back: "Retour", titleLabel: "Titre", storyLabel: "Histoire", photosLabel: "Photos", choosePhotos: "Choisir des photos", noPhotosSelected: "Aucune photo selectionnee", photosSelectedSuffix: " selectionnees", save: "Enregistrer dans Haven" },
  es: { ...EN, brand: "Nuevo recuerdo", title: "Captura este momento", back: "Volver", titleLabel: "Titulo", storyLabel: "Historia", photosLabel: "Fotos", choosePhotos: "Elegir fotos", noPhotosSelected: "Ninguna foto seleccionada", photosSelectedSuffix: " seleccionadas", save: "Guardar en Haven" },
  de: { ...EN, brand: "Neue Erinnerung", title: "Halte diesen Moment fest", back: "Zuruck", titleLabel: "Titel", storyLabel: "Geschichte", photosLabel: "Fotos", choosePhotos: "Fotos auswahlen", noPhotosSelected: "Keine Fotos ausgewahlt", photosSelectedSuffix: " ausgewahlt", save: "In Haven speichern" },
  it: { ...EN, brand: "Nuovo ricordo", title: "Cattura questo momento", back: "Indietro", titleLabel: "Titolo", storyLabel: "Storia", photosLabel: "Foto", choosePhotos: "Scegli foto", noPhotosSelected: "Nessuna foto selezionata", photosSelectedSuffix: " selezionate", save: "Salva in Haven" },
};
