const EN = {
  brand: "New Memory",
  title: "Capture this moment",
  back: "Back",
  titleLabel: "Title",
  titlePlaceholder: "A quiet title...",
  storyLabel: "Story",
  storyPlaceholder: "Write what this memory means to you...",
  photosLabel: "Photos",
  choosePhotos: "Choose photos",
  noPhotosSelected: "No photos selected",
  photosSelectedSuffix: " selected",
  photosHint: "Select 1 or more photos (max 6). Auto-compressed on device.",
  photosCountPrefix: "(",
  photosCountSuffix: ")",
  voiceTitlePrefix: "Voice note (max ",
  voiceTitleSuffix: "s)",
  micPermissionPromptHint: "Microphone permission is required to record voice notes.",
  micPermissionDeniedHint:
    "Microphone access is blocked. Tap Enable Microphone, then allow access in your browser or app settings.",
  micUnavailableNoGetUserMedia:
    "This browser does not support microphone capture (getUserMedia). Try Safari or Chrome on a newer OS.",
  micUnavailableNoMediaRecorder:
    "This browser can open microphone but cannot record audio (MediaRecorder unavailable). Please update browser/OS or switch browser.",
  micUnavailableInsecureContext:
    "Microphone recording requires HTTPS (or localhost). Open Haven from a secure URL.",
  requestMicPermission: "Enable Microphone",
  requestingMicPermission: "Requesting permission...",
  record: "Record Voice",
  stopPrefix: "Stop (",
  stopSuffix: "s)",
  removeVoice: "Remove Voice",
  saving: "Saving...",
  save: "Save Draft",
  sealNow: "Seal with Ring Now",
  haptic: "Haptic feedback",
  sound: "Success sound",
  soundSaveOnly: "Sound only on save success",
  privacyHint:
    "Saving creates a local draft only. Final seal requires touching your ring.",
  feedbackCompressing: "Compressing photos...",
  feedbackAddedPhotosPrefix: "Added ",
  feedbackAddedPhotosSuffix: " photo(s).",
  feedbackMaxPhotosPrefix: "Max ",
  feedbackMaxPhotosSuffix: " photos allowed.",
  feedbackPhotoError: "Could not process photos. Please try again.",
  feedbackVoiceCaptured: "Voice note captured.",
  feedbackMicPermissionGranted: "Microphone access enabled.",
  feedbackMicPermissionDenied:
    "Microphone permission denied. Please enable microphone access in browser/app settings.",
  feedbackMicNeedPermissionFirst: "Please tap Enable Microphone first.",
  feedbackMicBusy:
    "Microphone is currently busy or blocked by another app/tab. Close other recording apps and try again.",
  feedbackMicUnavailable: "Microphone unavailable. Please check permissions.",
  feedbackNeedContent: "Add some memory content before saving.",
  feedbackSavingLocal: "Saving draft locally...",
  feedbackSaved: "Draft saved. Touch your ring to seal.",
  feedbackReadyToSeal: "Ready to seal. Touch your ring now.",
  feedbackSaveFailed: "Save failed.",
  feedbackReadyNext: "Ready for your next memory.",
  untitled: "Untitled memory",
  canvasUnavailable: "Canvas not available.",
  compressionFailed: "Compression failed.",
  invalidImage: "Invalid image file.",
  readBinaryFailed: "Failed to read binary data.",
  sealPromptTitle: "Final step: touch your ring",
  sealPromptBody:
    "Hold your ring near the back of your phone now. Sealing is completed only after the ring touch is detected.",
  sealPromptDone: "I touched the ring",
  sealPromptClose: "Close",
};

export const NEW_MEMORY_PAGE_CONTENT = {
  en: EN,
  fr: { ...EN, brand: "Nouveau souvenir", title: "Capturez ce moment", back: "Retour", titleLabel: "Titre", storyLabel: "Histoire", photosLabel: "Photos", choosePhotos: "Choisir des photos", noPhotosSelected: "Aucune photo selectionnee", photosSelectedSuffix: " selectionnees", save: "Enregistrer dans Haven" },
  es: { ...EN, brand: "Nuevo recuerdo", title: "Captura este momento", back: "Volver", titleLabel: "Titulo", storyLabel: "Historia", photosLabel: "Fotos", choosePhotos: "Elegir fotos", noPhotosSelected: "Ninguna foto seleccionada", photosSelectedSuffix: " seleccionadas", save: "Guardar en Haven" },
  de: { ...EN, brand: "Neue Erinnerung", title: "Halte diesen Moment fest", back: "Zuruck", titleLabel: "Titel", storyLabel: "Geschichte", photosLabel: "Fotos", choosePhotos: "Fotos auswahlen", noPhotosSelected: "Keine Fotos ausgewahlt", photosSelectedSuffix: " ausgewahlt", save: "In Haven speichern" },
  it: { ...EN, brand: "Nuovo ricordo", title: "Cattura questo momento", back: "Indietro", titleLabel: "Titolo", storyLabel: "Storia", photosLabel: "Foto", choosePhotos: "Scegli foto", noPhotosSelected: "Nessuna foto selezionata", photosSelectedSuffix: " selezionate", save: "Salva in Haven" },
};
