const EN = {
  kicker: "Link your ring",
  title: "Touch your Haven ring",
  introBody: "Hold your Haven ring near your phone to link it to your account.",
  ctaAddRing: "Get started",
  ctaSkip: "Skip for now",
  scanTitle: "Touch your ring",
  scanBody: "Hold your Haven ring steady near your phone until we detect it.",
  scanCta: "Start scan",
  scanWorking: "Reading ring…",
  scanOrderTitle: "",
  scanOrderStep1: "",
  scanOrderStep2: "",
  scanRetry: "Try again",
  statusBindingTitle: "Linking ring",
  statusBindingScanning: "Hold your ring near your phone",
  statusBindingDetected: "Ring detected",
  iosNfcTitle: "Touch your ring",
  iosNfcBody: "Hold your Haven ring near the top of your iPhone.",
  installRecommendedTitle: "Add to Home Screen",
  installRecommendedBody: "For the smoothest NFC experience on iPhone, add Haven to your Home Screen.",
  continueInBrowserCta: "Continue in browser",
  installNowCta: "Add to Home Screen",
  installOptionalLater: "",
  installDoneHint: "Haven is on your Home Screen",
  installConsentTitle: "Add to Home Screen",
  installConsentBody: "This creates a Home Screen shortcut for faster NFC. You can skip and set it up later.",
  installConsentRevoke: "",
  installConsentConfirm: "Continue",
  installConsentCancel: "Cancel",
  installSuppressConfirmLabel: "Don't ask again",
  installSuccessNotice: "Added to Home Screen",
  iosInstallGuideCta: "Install guide",
  iosInstallGuideTitle: "Add Haven to Home Screen",
  iosInstallGuideTone: "",
  iosInstallGuideStep1: "Tap the top-right Share button in Safari.",
  iosInstallGuideStep2: "Select Add to Home Screen.",
  iosInstallGuideStep3: "Confirm Add.",
  iosInstallGuideStep4: "Tap Add, then open Haven from the new Home Screen icon.",
  iosInstallGuideScreenshotHint1:
    "Screenshot hint: look for Safari Share sheet with 'Add to Home Screen'.",
  iosInstallGuideScreenshotHint2:
    "Screenshot hint: after adding, confirm Haven icon appears on Home Screen.",
  useOpenedRingLinkCta: "Use this ring",
  useOpenedRingLinkHint: "",
  noOpenedRingLinkHint: "",
  installStateReady: "",
  installStateManual: "",
  installPreparingTimeout: "",
  installReadyAfterDelay: "",
  ringLinkDetected: "Ring link detected",
  ringLinkNotDetected: "Touch your ring to continue",
  iosInstallSafetyTitle: "",
  iosInstallSafetyBrief: "",
  iosInstallSafetyBody: "",
  iosInstallSafetyPrivacy: "",
  iosInstallSafetyExpand: "Details",
  iosInstallSafetyCollapse: "Hide details",
  iosInstallGuideSteps:
    "On iPhone Safari:\n1) Tap the Share button.\n2) Choose 'Add to Home Screen'.\n3) Confirm Add.\n4) Return to Home Screen and open Haven from the new icon.\n\nSafety note:\n- This only creates a shortcut icon.\n- It does not grant extra device permissions.\n- You can remove the icon anytime.",
  copyLinkCta: "Copy site link",
  copyLinkDone: "Site link copied. Paste it in Safari, then Add to Home Screen.",
  copyLinkFailed: "Could not copy link automatically. Please copy the URL from your browser.",
  androidOk: "Got it",
  verifyTitle: "Confirm it's you",
  verifyBody: "Enter your device password or recovery code.",
  verifyPassword: "Device password",
  verifyRecovery: "Recovery code",
  verifyCta: "Verify",
  verifyWorking: "Verifying…",
  verifyError: "Verification failed",
  needSecurityTitle: "Set a device password",
  needSecurityBody: "Set a device password in Haven Settings before linking a ring.",
  needSecurityResumeHint: "Continue when you're ready.",
  needSecurityStillMissing: "A device password is still required.",
  continueAfterSecurity: "Continue",
  setupPasswordLabel: "Device password",
  setupPasswordPlaceholder: "At least 6 characters",
  setupPasswordConfirmLabel: "Confirm password",
  setupPasswordConfirmPlaceholder: "Enter again",
  setupSecurityCta: "Continue",
  setupSecurityWorking: "Saving…",
  setupSecurityDone: "Password saved",
  setupSecurityFailed: "Could not save password",
  setupPasswordTooShort: "Use at least 6 characters",
  setupPasswordMismatch: "Passwords do not match",
  setupRecoveryHint: "Save your recovery code somewhere safe.",
  goSettings: "Open Settings",
  nameTitle: "Name your ring",
  nameBody: "",
  namePlaceholder: "Ring",
  colorLabel: "Color",
  iconLabel: "Icon",
  nameCta: "Done",
  rewriteTitle: "Advanced: Rewrite ring link (Android)",
  rewriteBody:
    "Optional for Android users. You can rewrite this ring to another trusted HTTPS link.",
  rewriteAction: "Rewrite Ring URL",
  rewriteWorking: "Rewriting ring link...",
  rewriteDone: "Ring link updated.",
  rewriteVerified: "Rewrite verified. The ring now opens the updated link.",
  rewriteInvalidUrl: "Please enter a valid HTTPS URL.",
  rewriteVerifyFailed:
    "Write finished, but read-back verification did not match. Please try once more.",
  rewriteFailed: "Could not rewrite ring link. Hold still and try again.",
  successTitle: "Ring linked",
  testSealNow: "Seal a memory",
  successBody: "",
  successEncourage: "",
  factoryStartLinkReadyIos: "",
  factoryStartLinkReadyAndroid: "",
  addAnother: "Link another ring",
  doneToHaven: "Continue",
  duplicateError: "This ring is already linked.",
  limitTitle: "Ring limit reached",
  limitBody: "Your Haven pair can have up to two active rings. Remove one before linking another.",
  limitCta: "Close",
  readError: "Could not read ring. Hold steady and try again.",
  cloudSignInRequired: "Sign in to link a ring.",
  cloudAccountRequired: "Sign in with your own account to link a ring.",
  cloudBindFailed: "Could not link ring. Try again.",
  privacyBindNotice: "",
  privacyPolicyLink: "Privacy",
  noNfcTitle: "NFC unavailable",
  noNfcBody: "Could not read NFC. Try again or check your phone settings.",
};

export const RING_SETUP_CONTENT = {
  en: EN,
  fr: {
    ...EN,
    kicker: "Configuration unique",
    title: "Configurez vos cles magiques",
    introBody:
      "Ajoutez vos bagues NFC comme acces rapide a votre espace de souvenirs. Chaque bague agit de la meme facon — nous recommandons au moins deux : une au quotidien et une en secours.",
    ctaAddRing: "Ajouter une bague NFC",
    ctaSkip: "Passer pour l'instant",
    scanTitle: "Approchez la bague du telephone",
    scanBody:
      "Posez la bague en haut du dos du telephone et gardez-la immobile quelques secondes.",
    scanCta: "Demarrer la lecture",
    scanWorking: "Ecoute NFC…",
    scanRetry: "Reessayer",
    statusBindingTitle: "Liaison d'une nouvelle bague",
    statusBindingScanning:
      "En attente du toucher de bague. Gardez la bague immobile pres du telephone.",
    statusBindingDetected:
      "Bague detectee. Ceci est une configuration de nouvelle bague ; confirmez votre identite, puis nommez-la.",
    iosNfcTitle: "NFC sur iPhone",
    iosNfcBody:
      "Votre bague est preconfiguree pour ouvrir ce sanctuaire. Nous allons maintenant la connecter a votre compte.",
    verifyTitle: "Confirmez votre identite",
    verifyBody:
      "Pour proteger votre compte, confirmez avec le mot de passe appareil ou le code de recuperation.",
    nameTitle: "Nommez cette bague",
    namePlaceholder: "ex. Quotidien, Secours, Voyage",
    successTitle: "Bague liee",
    successBody:
      "Cette bague sert desormais pour l'acces rapide et le scellement. Touchez une bague liee pour revenir au Haven.",
    addAnother: "Ajouter une autre bague",
    doneToHaven: "Aller a mon espace souvenirs",
    limitTitle: "Limite de bagues",
    limitBody: "Deux bagues maximum par Haven, une par compte partenaire.",
  },
  es: {
    ...EN,
    kicker: "Configuracion inicial",
    title: "Configura tus llaves magicas",
    introBody:
      "Anade tus anillos NFC como acceso rapido a tu espacio privado. Cada anillo funciona igual — recomendamos al menos dos: uno diario y otro de respaldo.",
    ctaAddRing: "Anadir anillo NFC",
    ctaSkip: "Saltar por ahora",
    scanTitle: "Acerca el anillo al telefono",
    scanCta: "Empezar escaneo",
    scanWorking: "Buscando NFC…",
    statusBindingTitle: "Vinculando nuevo anillo",
    statusBindingScanning:
      "Esperando el toque del anillo. Manténlo quieto cerca del teléfono.",
    statusBindingDetected:
      "Anillo detectado. Este es el flujo para vincular un nuevo anillo; confirma tu identidad y ponle nombre.",
    iosNfcTitle: "NFC en iPhone",
    verifyTitle: "Confirma que eres tu",
    nameTitle: "Nombre del anillo",
    successTitle: "Anillo vinculado",
    addAnother: "Anadir otro anillo",
    doneToHaven: "Ir a mi espacio",
    limitTitle: "Limite de anillos",
    limitBody: "Maximo dos anillos por Haven, uno por cuenta de cada pareja.",
  },
  de: {
    ...EN,
    kicker: "Einmalige Einrichtung",
    title: "Richte deine Schlussel ein",
    introBody:
      "Fu NFC-Ringe als Schnellzugriff fur deinen privaten Raum hinzu. Jeder Ring ist gleich — empfohlen sind mindestens zwei: einer fur jeden Tag und einer als Backup.",
    ctaAddRing: "NFC-Ring hinzufugen",
    ctaSkip: "Uberspringen",
    scanTitle: "Ring ans Telefon halten",
    scanCta: "Scan starten",
    scanWorking: "NFC wird gesucht…",
    statusBindingTitle: "Neuen Ring verknüpfen",
    statusBindingScanning:
      "Warte auf Ring-Berührung. Halte den Ring ruhig nahe ans Telefon.",
    statusBindingDetected:
      "Ring erkannt. Dies ist die Einrichtung eines neuen Rings; bestätige deine Identität und benenne ihn.",
    iosNfcTitle: "NFC auf dem iPhone",
    verifyTitle: "Bestatige deine Identitat",
    nameTitle: "Ring benennen",
    successTitle: "Ring verknupft",
    addAnother: "Weiteren Ring hinzufugen",
    doneToHaven: "Zu meinem Bereich",
    limitTitle: "Ring-Limit",
    limitBody: "Maximal zwei Ringe, eines pro Konto.",
  },
  it: {
    ...EN,
    kicker: "Configurazione una tantum",
    title: "Imposta le tue chiavi magiche",
    introBody:
      "Aggiungi gli anelli NFC come accesso rapido al tuo spazio privato. Ogni anello e uguale — consigliati almeno due: uno per il giorno e uno di riserva.",
    ctaAddRing: "Aggiungi anello NFC",
    ctaSkip: "Salta per ora",
    scanTitle: "Avvicina l'anello al telefono",
    scanCta: "Avvia scansione",
    scanWorking: "Ascolto NFC…",
    statusBindingTitle: "Collegamento nuovo anello",
    statusBindingScanning:
      "In attesa del tocco dell'anello. Tienilo fermo vicino al telefono.",
    statusBindingDetected:
      "Anello rilevato. Questo è il flusso per collegare un nuovo anello; conferma la tua identità e dagli un nome.",
    iosNfcTitle: "NFC su iPhone",
    verifyTitle: "Conferma la tua identita",
    nameTitle: "Nome dell'anello",
    successTitle: "Anello collegato",
    addAnother: "Aggiungi un altro anello",
    doneToHaven: "Vai al mio spazio",
    limitTitle: "Limite anelli",
    limitBody: "Massimo due anelli, uno per account.",
  },
};
