const EN = {
  kicker: "绑定",
  title: "请贴上戒指",
  introBody: "请贴上戒指",
  ctaAddRing: "开始",
  ctaSkip: "跳过",
  scanTitle: "请贴上戒指",
  scanBody: "请贴上戒指",
  scanCta: "开始",
  scanWorking: "读取中",
  scanOrderTitle: "",
  scanOrderStep1: "",
  scanOrderStep2: "",
  scanRetry: "重试",
  statusBindingTitle: "绑定中",
  statusBindingScanning: "请贴上戒指",
  statusBindingDetected: "已读取",
  iosNfcTitle: "请贴上戒指",
  iosNfcBody: "请贴上戒指",
  installRecommendedTitle: "安装",
  installRecommendedBody: "可稍后设置",
  continueInBrowserCta: "继续",
  installNowCta: "安装",
  installOptionalLater: "",
  installDoneHint: "已安装",
  installConsentTitle: "安装",
  installConsentBody: "可稍后设置",
  installConsentRevoke: "",
  installConsentConfirm: "继续",
  installConsentCancel: "取消",
  installSuppressConfirmLabel: "不再提示",
  installSuccessNotice: "已安装",
  iosInstallGuideCta: "安装说明",
  iosInstallGuideTitle: "安装",
  iosInstallGuideTone: "",
  iosInstallGuideStep1: "Tap the top-right Share button in Safari.",
  iosInstallGuideStep2: "Select Add to Home Screen.",
  iosInstallGuideStep3: "Confirm Add.",
  iosInstallGuideStep4: "Tap Add, then open Haven from the new Home Screen icon.",
  iosInstallGuideScreenshotHint1:
    "Screenshot hint: look for Safari Share sheet with 'Add to Home Screen'.",
  iosInstallGuideScreenshotHint2:
    "Screenshot hint: after adding, confirm Haven icon appears on Home Screen.",
  useOpenedRingLinkCta: "使用",
  useOpenedRingLinkHint: "",
  noOpenedRingLinkHint: "",
  installStateReady: "",
  installStateManual: "",
  installPreparingTimeout: "",
  installReadyAfterDelay: "",
  ringLinkDetected: "已读取",
  ringLinkNotDetected: "请贴上戒指",
  iosInstallSafetyTitle: "",
  iosInstallSafetyBrief: "",
  iosInstallSafetyBody: "",
  iosInstallSafetyPrivacy: "",
  iosInstallSafetyExpand: "详情",
  iosInstallSafetyCollapse: "收起",
  iosInstallGuideSteps:
    "On iPhone Safari:\n1) Tap the Share button.\n2) Choose 'Add to Home Screen'.\n3) Confirm Add.\n4) Return to Home Screen and open Haven from the new icon.\n\nSafety note:\n- This only creates a shortcut icon.\n- It does not grant extra device permissions.\n- You can remove the icon anytime.",
  copyLinkCta: "Copy site link",
  copyLinkDone: "Site link copied. Paste it in Safari, then Add to Home Screen.",
  copyLinkFailed: "Could not copy link automatically. Please copy the URL from your browser.",
  androidOk: "Got it",
  verifyTitle: "确认身份",
  verifyBody: "请输入密码",
  verifyPassword: "设备密码",
  verifyRecovery: "恢复码",
  verifyCta: "确认",
  verifyWorking: "确认中",
  verifyError: "验证失败",
  needSecurityTitle: "设置密码",
  needSecurityBody: "请先设置密码",
  needSecurityResumeHint: "请继续",
  needSecurityStillMissing: "请先设置密码",
  continueAfterSecurity: "继续",
  setupPasswordLabel: "设置密码",
  setupPasswordPlaceholder: "至少 6 位",
  setupPasswordConfirmLabel: "确认密码",
  setupPasswordConfirmPlaceholder: "再输入一次",
  setupSecurityCta: "继续",
  setupSecurityWorking: "设置中",
  setupSecurityDone: "已设置",
  setupSecurityFailed: "设置失败",
  setupPasswordTooShort: "至少 6 位",
  setupPasswordMismatch: "两次密码不一致",
  setupRecoveryHint: "恢复码",
  goSettings: "设置",
  nameTitle: "命名戒指",
  nameBody: "",
  namePlaceholder: "Ring",
  colorLabel: "颜色",
  iconLabel: "图标",
  nameCta: "完成",
  rewriteTitle: "Advanced: Rewrite ring link (Android)",
  rewriteBody:
    "Optional for Android users. You can rewrite this ring to another trusted HTTPS link.",
  rewriteAction: "Rewrite Ring URL",
  rewriteWorking: "Rewriting ring link...",
  rewriteDone: "Ring link updated.",
  rewriteVerified: "Rewrite verified. The ring now opens the updated link.",
  rewriteInvalidUrl: "Please enter a valid HTTPS URL.",
  rewriteVerifyFailed:
    "Write finished, but read-back verification did not match. Please try once more.",
  rewriteFailed: "Could not rewrite ring link. Hold still and try again.",
  successTitle: "已绑定",
  testSealNow: "去封印",
  successBody: "",
  successEncourage: "",
  factoryStartLinkReadyIos: "",
  factoryStartLinkReadyAndroid: "",
  addAnother: "再绑定",
  doneToHaven: "继续",
  duplicateError: "已绑定",
  limitTitle: "已达上限",
  limitBody: "请先移除一个戒指",
  limitCta: "关闭",
  readError: "贴戒指失败，请重试",
  cloudSignInRequired: "请先登录",
  cloudAccountRequired: "请先登录",
  cloudBindFailed: "绑定失败，请重试",
  privacyBindNotice: "",
  privacyPolicyLink: "隐私",
  noNfcTitle: "无法读取 NFC",
  noNfcBody: "请重试",
};

export const RING_SETUP_CONTENT = {
  en: EN,
  fr: {
    ...EN,
    kicker: "Configuration unique",
    title: "Configurez vos cles magiques",
    introBody:
      "Ajoutez vos bagues NFC comme acces rapide a votre espace de souvenirs. Chaque bague agit de la meme facon — nous recommandons au moins deux : une au quotidien et une en secours.",
    ctaAddRing: "Ajouter une bague NFC",
    ctaSkip: "Passer pour l'instant",
    scanTitle: "Approchez la bague du telephone",
    scanBody:
      "Posez la bague en haut du dos du telephone et gardez-la immobile quelques secondes.",
    scanCta: "Demarrer la lecture",
    scanWorking: "Ecoute NFC…",
    scanRetry: "Reessayer",
    statusBindingTitle: "Liaison d'une nouvelle bague",
    statusBindingScanning:
      "En attente du toucher de bague. Gardez la bague immobile pres du telephone.",
    statusBindingDetected:
      "Bague detectee. Ceci est une configuration de nouvelle bague ; confirmez votre identite, puis nommez-la.",
    iosNfcTitle: "NFC sur iPhone",
    iosNfcBody:
      "Votre bague est preconfiguree pour ouvrir ce sanctuaire. Nous allons maintenant la connecter a votre compte.",
    verifyTitle: "Confirmez votre identite",
    verifyBody:
      "Pour proteger votre compte, confirmez avec le mot de passe appareil ou le code de recuperation.",
    nameTitle: "Nommez cette bague",
    namePlaceholder: "ex. Quotidien, Secours, Voyage",
    successTitle: "Bague liee",
    successBody:
      "Cette bague sert desormais pour l'acces rapide et le scellement. Touchez une bague liee pour revenir au Haven.",
    addAnother: "Ajouter une autre bague",
    doneToHaven: "Aller a mon espace souvenirs",
    limitTitle: "Limite de bagues",
    limitBody: "Deux bagues maximum par Haven, une par compte partenaire.",
  },
  es: {
    ...EN,
    kicker: "Configuracion inicial",
    title: "Configura tus llaves magicas",
    introBody:
      "Anade tus anillos NFC como acceso rapido a tu espacio privado. Cada anillo funciona igual — recomendamos al menos dos: uno diario y otro de respaldo.",
    ctaAddRing: "Anadir anillo NFC",
    ctaSkip: "Saltar por ahora",
    scanTitle: "Acerca el anillo al telefono",
    scanCta: "Empezar escaneo",
    scanWorking: "Buscando NFC…",
    statusBindingTitle: "Vinculando nuevo anillo",
    statusBindingScanning:
      "Esperando el toque del anillo. Manténlo quieto cerca del teléfono.",
    statusBindingDetected:
      "Anillo detectado. Este es el flujo para vincular un nuevo anillo; confirma tu identidad y ponle nombre.",
    iosNfcTitle: "NFC en iPhone",
    verifyTitle: "Confirma que eres tu",
    nameTitle: "Nombre del anillo",
    successTitle: "Anillo vinculado",
    addAnother: "Anadir otro anillo",
    doneToHaven: "Ir a mi espacio",
    limitTitle: "Limite de anillos",
    limitBody: "Maximo dos anillos por Haven, uno por cuenta de cada pareja.",
  },
  de: {
    ...EN,
    kicker: "Einmalige Einrichtung",
    title: "Richte deine Schlussel ein",
    introBody:
      "Fu NFC-Ringe als Schnellzugriff fur deinen privaten Raum hinzu. Jeder Ring ist gleich — empfohlen sind mindestens zwei: einer fur jeden Tag und einer als Backup.",
    ctaAddRing: "NFC-Ring hinzufugen",
    ctaSkip: "Uberspringen",
    scanTitle: "Ring ans Telefon halten",
    scanCta: "Scan starten",
    scanWorking: "NFC wird gesucht…",
    statusBindingTitle: "Neuen Ring verknüpfen",
    statusBindingScanning:
      "Warte auf Ring-Berührung. Halte den Ring ruhig nahe ans Telefon.",
    statusBindingDetected:
      "Ring erkannt. Dies ist die Einrichtung eines neuen Rings; bestätige deine Identität und benenne ihn.",
    iosNfcTitle: "NFC auf dem iPhone",
    verifyTitle: "Bestatige deine Identitat",
    nameTitle: "Ring benennen",
    successTitle: "Ring verknupft",
    addAnother: "Weiteren Ring hinzufugen",
    doneToHaven: "Zu meinem Bereich",
    limitTitle: "Ring-Limit",
    limitBody: "Maximal zwei Ringe, eines pro Konto.",
  },
  it: {
    ...EN,
    kicker: "Configurazione una tantum",
    title: "Imposta le tue chiavi magiche",
    introBody:
      "Aggiungi gli anelli NFC come accesso rapido al tuo spazio privato. Ogni anello e uguale — consigliati almeno due: uno per il giorno e uno di riserva.",
    ctaAddRing: "Aggiungi anello NFC",
    ctaSkip: "Salta per ora",
    scanTitle: "Avvicina l'anello al telefono",
    scanCta: "Avvia scansione",
    scanWorking: "Ascolto NFC…",
    statusBindingTitle: "Collegamento nuovo anello",
    statusBindingScanning:
      "In attesa del tocco dell'anello. Tienilo fermo vicino al telefono.",
    statusBindingDetected:
      "Anello rilevato. Questo è il flusso per collegare un nuovo anello; conferma la tua identità e dagli un nome.",
    iosNfcTitle: "NFC su iPhone",
    verifyTitle: "Conferma la tua identita",
    nameTitle: "Nome dell'anello",
    successTitle: "Anello collegato",
    addAnother: "Aggiungi un altro anello",
    doneToHaven: "Vai al mio spazio",
    limitTitle: "Limite anelli",
    limitBody: "Massimo due anelli, uno per account.",
  },
};
