const EN = {
  kicker: "One-time setup",
  title: "Set up your magic keys",
  introBody:
    "Add your NFC rings as quick access keys to your private memory space. Any ring you add works the same way — we recommend at least two: one for daily wear and one kept safe as backup.",
  ctaAddRing: "Add NFC ring",
  ctaSkip: "Skip for now",
  scanTitle: "Hold your ring to the phone",
  scanBody:
    "Rest the ring on the upper back of your phone and keep it still for a few seconds.",
  scanCta: "Start scanning",
  scanWorking: "Listening for NFC…",
  scanRetry: "Try again",
  iosNfcTitle: "NFC setup on iPhone",
  iosNfcBody:
    "Web NFC is not available in iPhone browsers. Add Haven to your Home Screen for the best PWA experience, and use an Android device or desktop Chrome when you need on-device NFC registration in the browser.",
  androidOk: "Got it",
  verifyTitle: "Confirm it's you",
  verifyBody:
    "To protect your account, confirm with your device password or recovery code. On supported devices, your platform may use Face ID, Touch ID, or a passkey with this step when enabled.",
  verifyPassword: "Device password",
  verifyRecovery: "Or recovery code",
  verifyCta: "Confirm",
  verifyWorking: "Verifying…",
  verifyError: "Verification failed. Check your password or code.",
  needSecurityTitle: "Device protection required",
  needSecurityBody:
    "Set a device password in Settings first. We use it to confirm sensitive steps like linking a ring — your ring alone is not enough.",
  goSettings: "Open Settings",
  nameTitle: "Name this ring",
  nameBody: "A short label helps you tell rings apart. You can change this later.",
  namePlaceholder: "e.g. Daily carry, Backup vault, Travel",
  colorLabel: "Color",
  iconLabel: "Icon",
  nameCta: "Save and finish",
  successTitle: "Ring linked",
  successBody:
    "This ring can now be used for quick access and sealing memories. Tap any linked ring to return to your Haven — no mode switching.",
  successEncourage:
    "Best practice: add a second ring and store it safely. If you lose one ring, your memories stay with your account.",
  addAnother: "Add another ring",
  doneToHaven: "Go to my memory space",
  duplicateError: "This ring is already in your list.",
  limitTitle: "Ring limit reached",
  limitBody:
    "You can link up to five rings. Remove or revoke one from Settings or your account tools before adding another.",
  limitCta: "Close",
  readError: "Could not read the ring. Hold it steady and try again.",
  cloudSignInRequired:
    "Sign in to your account (e.g. enable cloud backup in Settings) before linking this ring to the server.",
  cloudAccountRequired:
    "Link a permanent sign-in (not a guest session) in Settings, then add your ring again.",
  cloudBindFailed: "Could not link the ring to your account. Please try again.",
  privacyBindNotice:
    "By registering a ring, you agree we store a secure fingerprint of the tag (not the raw UID) for login and limits — see our Privacy Policy.",
  privacyPolicyLink: "Privacy Policy",
  noNfcTitle: "NFC not available in this browser",
  noNfcBody:
    "Use Chrome on an Android phone with NFC, or try another device. You can still use Haven; in-browser ring registration needs Web NFC (common on Android).",
};

export const RING_SETUP_CONTENT = {
  en: EN,
  fr: {
    ...EN,
    kicker: "Configuration unique",
    title: "Configurez vos cles magiques",
    introBody:
      "Ajoutez vos bagues NFC comme acces rapide a votre espace de souvenirs. Chaque bague agit de la meme facon — nous recommandons au moins deux : une au quotidien et une en secours.",
    ctaAddRing: "Ajouter une bague NFC",
    ctaSkip: "Passer pour l'instant",
    scanTitle: "Approchez la bague du telephone",
    scanBody:
      "Posez la bague en haut du dos du telephone et gardez-la immobile quelques secondes.",
    scanCta: "Demarrer la lecture",
    scanWorking: "Ecoute NFC…",
    scanRetry: "Reessayer",
    iosNfcTitle: "NFC sur iPhone",
    iosNfcBody:
      "Le NFC Web n'est pas disponible sur Safari iPhone. Ajoutez Haven a l'ecran d'accueil et utilisez Chrome Android ou bureau pour l'enregistrement NFC dans le navigateur.",
    verifyTitle: "Confirmez votre identite",
    verifyBody:
      "Pour proteger votre compte, confirmez avec le mot de passe appareil ou le code de recuperation.",
    nameTitle: "Nommez cette bague",
    namePlaceholder: "ex. Quotidien, Secours, Voyage",
    successTitle: "Bague liee",
    successBody:
      "Cette bague sert desormais pour l'acces rapide et le scellement. Touchez une bague liee pour revenir au Haven.",
    addAnother: "Ajouter une autre bague",
    doneToHaven: "Aller a mon espace souvenirs",
    limitTitle: "Limite de bagues",
    limitBody: "Jusqu'a cinq bagues. Retirez-en une avant d'en ajouter une nouvelle.",
  },
  es: {
    ...EN,
    kicker: "Configuracion inicial",
    title: "Configura tus llaves magicas",
    introBody:
      "Anade tus anillos NFC como acceso rapido a tu espacio privado. Cada anillo funciona igual — recomendamos al menos dos: uno diario y otro de respaldo.",
    ctaAddRing: "Anadir anillo NFC",
    ctaSkip: "Saltar por ahora",
    scanTitle: "Acerca el anillo al telefono",
    scanCta: "Empezar escaneo",
    scanWorking: "Buscando NFC…",
    iosNfcTitle: "NFC en iPhone",
    verifyTitle: "Confirma que eres tu",
    nameTitle: "Nombre del anillo",
    successTitle: "Anillo vinculado",
    addAnother: "Anadir otro anillo",
    doneToHaven: "Ir a mi espacio",
    limitTitle: "Limite de anillos",
    limitBody: "Hasta cinco anillos. Quita uno antes de anadir otro.",
  },
  de: {
    ...EN,
    kicker: "Einmalige Einrichtung",
    title: "Richte deine Schlussel ein",
    introBody:
      "Fu NFC-Ringe als Schnellzugriff fur deinen privaten Raum hinzu. Jeder Ring ist gleich — empfohlen sind mindestens zwei: einer fur jeden Tag und einer als Backup.",
    ctaAddRing: "NFC-Ring hinzufugen",
    ctaSkip: "Uberspringen",
    scanTitle: "Ring ans Telefon halten",
    scanCta: "Scan starten",
    scanWorking: "NFC wird gesucht…",
    iosNfcTitle: "NFC auf dem iPhone",
    verifyTitle: "Bestatige deine Identitat",
    nameTitle: "Ring benennen",
    successTitle: "Ring verknupft",
    addAnother: "Weiteren Ring hinzufugen",
    doneToHaven: "Zu meinem Bereich",
    limitTitle: "Ring-Limit",
    limitBody: "Maximal funf Ringe. Entferne einen, bevor du einen neuen addierst.",
  },
  it: {
    ...EN,
    kicker: "Configurazione una tantum",
    title: "Imposta le tue chiavi magiche",
    introBody:
      "Aggiungi gli anelli NFC come accesso rapido al tuo spazio privato. Ogni anello e uguale — consigliati almeno due: uno per il giorno e uno di riserva.",
    ctaAddRing: "Aggiungi anello NFC",
    ctaSkip: "Salta per ora",
    scanTitle: "Avvicina l'anello al telefono",
    scanCta: "Avvia scansione",
    scanWorking: "Ascolto NFC…",
    iosNfcTitle: "NFC su iPhone",
    verifyTitle: "Conferma la tua identita",
    nameTitle: "Nome dell'anello",
    successTitle: "Anello collegato",
    addAnother: "Aggiungi un altro anello",
    doneToHaven: "Vai al mio spazio",
    limitTitle: "Limite anelli",
    limitBody: "Massimo cinque anelli. Rimuovine uno prima di aggiungerne un altro.",
  },
};
