const EN = {
  brand: "Settings",
  title: "Privacy-first controls",
  upgradeSectionTitle: "Haven Plus",
  upgradeSectionBody:
    "Haven Plus includes Seal with Ring and optional encrypted cloud backup. Details in Help.",
  upgradeSectionCta: "View plans & pricing",
  back: "Back",
  localSectionTitle: "Local data",
  localDefault:
    "Memories are sealed on this device first. Cloud backup is optional with Haven Plus.",
  localStorageTight:
    "Local storage is getting full — consider removing older memories.",
  localStorageCleanupCta: "Free up local storage",
  localStorageCleanupHint:
    "Removes all memories from this device. Export a backup first if you need one.",
  backgroundSyncPendingOne:
    "1 sealed memory finishing backup in the background.",
  backgroundSyncPendingMany:
    "{n} sealed memories finishing backup in the background.",
  backgroundSyncOffline: "Will continue backup when you're back online.",
  loadingStats: "Loading local stats...",
  storageUnavailable: "Unavailable",
  storedStatsLabel: "Stored memories",
  estimatedStorageLabel: "Estimated storage",
  exportBackup: "Export Backup",
  clearAll: "Clear All Memories",
  deviceSecuritySectionTitle: "Trusted devices",
  deviceSecurityEnabled:
    "This device is protected with a Haven password for sensitive actions.",
  deviceSecurityNotEnabled:
    "Set a device password to protect sealed memories and sensitive actions. See Help.",
  deviceTrustedAtLabel: "Trusted on",
  revokeDevice: "Revoke",
  confirmRevokeDevice:
    "Remove this device trust? It will require password or recovery code next time.",
  deviceRevoked: "Device access revoked.",
  cloudSectionTitle: "Cloud backup (Haven Plus)",
  cloudQuotaNote: "50 GB hard cap per account. Uploads are encrypted, compressed, and chunked.",
  cloudSupplementsNote:
    "Notes stay on this device. With Haven Plus, memories and notes sync across your signed-in devices.",
  cloudStorageFull: "Storage full. Upgrade or delete old memories.",
  cloudToggleLabel:
    "Enable encrypted cloud backup (Plus, 50 GB cap). You can turn this off anytime.",
  cloudOff: "Cloud backup is off — your memories stay on this device only.",
  cloudEnabledNoSignIn: "Cloud backup is enabled but not signed in yet.",
  cloudEnabledSignedIn: "Cloud backup is enabled and linked to your Haven sign-in.",
  cloudRequiresPlus: "Haven Plus is required for encrypted cloud backup.",
  cloudPairSharingNote:
    "Pair sealed-memory sync does not use this switch — it works through Rings after both accounts join the same Haven.",
  cloudCouplePlusNote:
    "Couples share one Haven Plus. One partner subscribes, both benefit. Cloud quota is shared for the Haven.",
  cloudBillingYou: "Your account pays for Haven Plus.",
  cloudBillingPartner: "Your partner's account pays for Haven Plus.",
  cloudBillingChoose: "Use my account for Haven Plus billing",
  signInApple: "Link Haven sign-in",
  signInAppleOAuth: "Sign in with Apple",
  backupNow: "Backup Now",
  restore: "Restore",
  deepSync: "Deep sync",
  deepSyncHint:
    "Full pair import and cloud note restore — use when switching devices or after a crash.",
  confirmDeepSync:
    "Run a deep sync? This may take longer and uses more memory than pull-to-refresh.",
  deepSyncRunning: "Running deep sync...",
  deepSyncDone: "Deep sync finished.",
  deepSyncFailed: "Deep sync could not finish.",
  unlink: "Unlink Account",
  feedbackSectionTitle: "Sounds & haptics",
  feedbackSoundsLabel: "Success sounds",
  feedbackHapticsLabel: "Haptic feedback",
  feedbackSoundsHint: "Short tones when you save or pin a memory.",
  feedbackHapticsHint: "A light tap on supported devices.",
  privacySectionTitle: "Privacy",
  riskOpsTitle: "High-risk actions need extra verification",
  riskOpsBody:
    "For your protection, these actions typically require secondary verification before execution.",
  requiresVerificationBadge: "Requires verification",
  verifyModalTitle: "Confirm with device verification",
  verifyModalBody:
    "Use your device password or recovery code to continue this protected action.",
  verifyPasswordPlaceholder: "Device password",
  verifyRecoveryPlaceholder: "Recovery code (optional)",
  verifyActionConfirm: "Verify and continue",
  verifyActionCancel: "Cancel",
  verifyActionFailed: "Verification failed. Please check and try again.",
  riskOpRingManage: "Add or unbind pair rings",
  riskOpExportMigrate: "Export or migrate protected data",
  riskOpDeleteSealed: "Delete sealed memories",
  riskOpRemoteRevoke: "Retire lost ring credentials",
  privacyLine1: "Sealed memories are stored on your device immediately — encrypted, local-first.",
  privacyLine2: "Cloud backup is optional and runs in the background when you enable Plus.",
  privacyNfcLine:
    "NFC bind/retire: we store only a secure fingerprint of the tag, not a naked UID. You can retire a lost ring from another signed-in device.",
  privacyUnbindLine:
    "Retiring a ring does not delete your sealed memories; it stops that ring from being used for sealing and it cannot be transferred to another Haven.",
  privacyE2eLine:
    "Your sealed memories are encrypted on supported flows. One account per person; your ring is for sealing only.",
  privacyPolicy: "View Privacy Policy",
  openHelp: "Open Help Center",
  confirmExport: "Export encrypted local backup file now?",
  preparingExport: "Preparing backup export...",
  exportDone: "Backup exported.",
  exportFailed: "Export failed.",
  confirmClear: "Delete all local memories from this device? This cannot be undone.",
  clearing: "Clearing local memories...",
  clearDone: "All local memories cleared.",
  clearFailed: "Could not clear memories.",
  confirmEnableCloud:
    "Enable optional cloud backup? Local-only mode remains available.",
  confirmDisableCloud:
    "Disable cloud backup? Existing local data will remain on this device.",
  cloudEnabledStatus: "Cloud backup enabled.",
  cloudDisabledStatus: "Cloud backup disabled.",
  confirmSignInApple: "Link your current Haven sign-in for optional cloud backup?",
  signingIn: "Linking Apple sign-in...",
  signInDone: "Apple backup account linked.",
  signInFailed: "Could not complete Apple sign-in.",
  confirmBackup:
    "Back up now? Haven Plus encrypts your backup before upload (memories and notes).",
  backingUp: "Running cloud backup...",
  backupDone: "Cloud backup completed.",
  backupFailed: "Cloud backup failed.",
  confirmRestore:
    "Restore from cloud? New notes from your other devices will merge in. Sealed content on this device stays as-is.",
  restoring: "Checking cloud backup...",
  restoreDone: "Cloud restore finished.",
  restoreFailed: "Cloud restore failed.",
  confirmUnlink: "Unlink cloud backup account from this device?",
  unlinkDone: "Cloud backup account unlinked.",
  loadStatsFailed: "Could not load local storage stats.",
  sessionSectionTitle: "Ring & session",
  keepSignedInLabel:
    "Stay signed in on this device. Sign-in uses your Apple, Google, or Email account only.",
  revokeAllNfcTitle: "Cloud-linked NFC rings",
  revokeAllNfcBody:
    "Retire ring credentials for this account. Lost rings stop working immediately and cannot be transferred.",
  revokeAllNfcButton: "Retire my ring credentials",
  confirmRevokeAllNfc:
    "Retire ALL NFC ring credentials for this account? Retired rings cannot be transferred to another Haven.",
  revokeAllNfcNeedSignIn: "Sign in with cloud backup first, then try again.",
  revokeAllNfcDone: "Retired {n} ring credential(s).",
  revokeAllNfcFailed: "Could not retire all rings.",
  temporarySectionTitle: "Temporary phone safety",
  temporaryModeLabel:
    "Temporary device mode (auto wipe local data after use).",
  temporaryModeHelp:
    "Use this on borrowed iPhone/Android devices. After finishing, tap secure exit to remove local memories, caches, and sessions from this phone.",
  temporaryExitButton: "Secure exit and wipe this phone",
  confirmTemporaryExit:
    "End this temporary session now? This will sign out and wipe local memories, cache, and tokens from this phone.",
  temporaryExitDone: "Temporary session ended. Local data has been wiped.",
  temporaryExitFailed: "Could not complete secure wipe. Please retry.",
  accountSectionTitle: "Account",
  accountLocalLine:
    "Sealed memories live on this device first. Optional cloud backup runs in the background.",
  accountCloudSignedIn: "Signed in for optional cloud backup.",
  accountCloudOff: "Not signed in for cloud backup.",
  subscriptionSectionTitle: "Subscription",
  subscriptionBody:
    "Free: local only. Plus: optional cloud backup and explicit sharing. See Help for billing.",
  subscriptionManageCta: "Manage subscription",
  ringsSectionTitle: "Partner",
  ringsBody: "",
  ringsManageCta: "Open Rings",
  ringsAddPartnerCta: "Add Partner",
  ringsLinkedStatus: "Linked with Partner",
  advancedSectionTitle: "Advanced",
  revokeAllNfcAdvancedSummary: "Lost ring — retire credentials",
  dataPrivacySectionTitle: "Data & privacy",
  legalSectionTitle: "Legal",
  termsLink: "Terms of Service",
  privacyContactLabel: "Privacy contact",
};

export const SETTINGS_CONTENT = {
  en: EN,
  fr: {
    ...EN,
    brand: "Réglages",
    title: "Contrôles axés confidentialité",
    back: "Retour",
    localSectionTitle: "Données locales",
    localDefault:
      "Par défaut : tout reste sur votre appareil. La sauvegarde cloud est optionnelle.",
    cloudSectionTitle: "Sauvegarde cloud optionnelle",
    privacySectionTitle: "Confidentialité",
    privacyPolicy: "Voir la politique de confidentialité",
    openHelp: "Ouvrir le centre d'aide",
  },
  es: {
    ...EN,
    brand: "Configuración",
    title: "Controles centrados en privacidad",
    back: "Volver",
    localSectionTitle: "Datos locales",
    localDefault:
      "Predeterminado: todo permanece en tu dispositivo. La copia en la nube es opcional.",
    cloudSectionTitle: "Copia en la nube opcional",
    privacySectionTitle: "Privacidad",
    privacyPolicy: "Ver política de privacidad",
    openHelp: "Abrir centro de ayuda",
  },
  de: {
    ...EN,
    brand: "Einstellungen",
    title: "Datenschutz zuerst",
    back: "Zurück",
    localSectionTitle: "Lokale Daten",
    localDefault: "Standard: Alles bleibt auf deinem Gerät. Cloud-Backup ist optional.",
    cloudSectionTitle: "Optionales Cloud-Backup",
    privacySectionTitle: "Datenschutz",
    privacyPolicy: "Datenschutzrichtlinie ansehen",
    openHelp: "Hilfecenter öffnen",
  },
  it: {
    ...EN,
    brand: "Impostazioni",
    title: "Controlli privacy-first",
    back: "Indietro",
    localSectionTitle: "Dati locali",
    localDefault:
      "Predefinito: tutto resta sul tuo dispositivo. Il backup cloud è opzionale.",
    cloudSectionTitle: "Backup cloud opzionale",
    privacySectionTitle: "Privacy",
    privacyPolicy: "Visualizza informativa privacy",
    openHelp: "Apri centro assistenza",
  },
};
