const EN = {
  brand: "Settings",
  title: "Privacy-first controls",
  upgradeSectionTitle: "Haven Plus",
  upgradeSectionBody:
    "Haven Plus unlocks Seal with Ring plus optional end-to-end encrypted cloud backup and sync for your private pair. Free plan keeps everything on this device only.",
  upgradeSectionCta: "View plans & pricing",
  back: "Back",
  localSectionTitle: "Local data",
  localDefault:
    "Free plan: memories stay on this device only (encrypted local storage). Cloud is optional with Haven Plus.",
  loadingStats: "Loading local stats...",
  storageUnavailable: "Unavailable",
  storedStatsLabel: "Stored memories",
  estimatedStorageLabel: "Estimated storage",
  exportBackup: "Export Backup",
  clearAll: "Clear All Memories",
  deviceSecuritySectionTitle: "Trusted devices",
  deviceSecurityEnabled:
    "This Haven is protected by a password on new devices. Trusted devices can open with ring tap only.",
  deviceSecurityNotEnabled:
    "Device protection is not initialized yet. Complete setup from ring quick access flow.",
  deviceTrustedAtLabel: "Trusted on",
  revokeDevice: "Revoke",
  confirmRevokeDevice:
    "Remove this device trust? It will require password or recovery code next time.",
  deviceRevoked: "Device access revoked.",
  cloudSectionTitle: "Cloud backup (Haven Plus)",
  cloudToggleLabel:
    "Enable encrypted cloud backup and sync (Plus). You can turn this off anytime.",
  cloudOff: "Cloud backup is off — your memories stay on this device only.",
  cloudEnabledNoSignIn: "Cloud backup is enabled but not signed in yet.",
  cloudEnabledSignedIn: "Cloud backup is enabled and linked.",
  signInApple: "Sign in with Apple",
  backupNow: "Backup Now",
  restore: "Restore",
  unlink: "Unlink Account",
  feedbackSectionTitle: "Sounds & haptics",
  feedbackSoundsLabel: "Success sounds",
  feedbackHapticsLabel: "Haptic feedback",
  feedbackSoundsHint: "Short tones when you save or pin a memory.",
  feedbackHapticsHint: "A light tap on supported devices.",
  privacySectionTitle: "Privacy",
  riskOpsTitle: "High-risk actions need extra verification",
  riskOpsBody:
    "For your protection, these actions typically require secondary verification before execution.",
  requiresVerificationBadge: "Requires verification",
  verifyModalTitle: "Confirm with device verification",
  verifyModalBody:
    "Use your device password or recovery code to continue this protected action.",
  verifyPasswordPlaceholder: "Device password",
  verifyRecoveryPlaceholder: "Recovery code (optional)",
  verifyActionConfirm: "Verify and continue",
  verifyActionCancel: "Cancel",
  verifyActionFailed: "Verification failed. Please check and try again.",
  riskOpRingManage: "Add or unbind pair rings",
  riskOpExportMigrate: "Export or migrate protected data",
  riskOpDeleteSealed: "Delete sealed memories",
  riskOpRemoteRevoke: "Retire lost ring credentials",
  privacyLine1: "All memories are stored locally on your device with encryption.",
  privacyLine2: "Cloud backup is completely optional.",
  privacyNfcLine:
    "NFC bind/retire: we store only a secure fingerprint of the tag, not a naked UID. You can retire a lost ring from another signed-in device.",
  privacyUnbindLine:
    "Retiring a ring does not delete your sealed memories; it stops that ring from being used for sealing and it cannot be transferred to another Haven.",
  privacyE2eLine:
    "Your sealed memories are protected with end-to-end encryption on supported flows. Rings are keys to your Haven, while each partner keeps their own account identity.",
  privacyPolicy: "View Privacy Policy",
  openHelp: "Open Help Center",
  confirmExport: "Export encrypted local backup file now?",
  preparingExport: "Preparing backup export...",
  exportDone: "Backup exported.",
  exportFailed: "Export failed.",
  confirmClear: "Delete all local memories from this device? This cannot be undone.",
  clearing: "Clearing local memories...",
  clearDone: "All local memories cleared.",
  clearFailed: "Could not clear memories.",
  confirmEnableCloud:
    "Enable optional cloud backup? Local-only mode remains available.",
  confirmDisableCloud:
    "Disable cloud backup? Existing local data will remain on this device.",
  cloudEnabledStatus: "Cloud backup enabled.",
  cloudDisabledStatus: "Cloud backup disabled.",
  confirmSignInApple: "Sign in with Apple for optional cloud backup now?",
  signingIn: "Linking Apple sign-in...",
  signInDone: "Apple backup account linked.",
  signInFailed: "Could not complete Apple sign-in.",
  confirmBackup: "Run cloud backup now? This may upload a snapshot of your local data where that feature is available.",
  backingUp: "Running cloud backup...",
  backupDone: "Cloud backup completed.",
  backupFailed: "Cloud backup failed.",
  confirmRestore:
    "Restore from cloud backup now? This action may overwrite local expectations.",
  restoring: "Checking cloud backup...",
  restoreDone: "Cloud restore completed.",
  restoreFailed: "Cloud restore failed.",
  confirmUnlink: "Unlink cloud backup account from this device?",
  unlinkDone: "Cloud backup account unlinked.",
  loadStatsFailed: "Could not load local storage stats.",
  sessionSectionTitle: "Ring & session",
  keepSignedInLabel:
    "Stay signed in on this device. Ring-only account login is disabled for shared Haven pairs.",
  revokeAllNfcTitle: "Cloud-linked NFC rings",
  revokeAllNfcBody:
    "Retire every ring credential for your Haven membership. Lost rings stop working immediately and cannot be transferred.",
  revokeAllNfcButton: "Retire my ring credentials",
  confirmRevokeAllNfc:
    "Retire ALL NFC ring credentials for this account? Retired rings cannot be transferred to another Haven.",
  revokeAllNfcNeedSignIn: "Sign in with cloud backup first, then try again.",
  revokeAllNfcDone: "Retired {n} ring credential(s).",
  revokeAllNfcFailed: "Could not retire all rings.",
  temporarySectionTitle: "Temporary phone safety",
  temporaryModeLabel:
    "Temporary device mode (auto wipe local data after use).",
  temporaryModeHelp:
    "Use this on borrowed iPhone/Android devices. After finishing, tap secure exit to remove local memories, caches, and sessions from this phone.",
  temporaryExitButton: "Secure exit and wipe this phone",
  confirmTemporaryExit:
    "End this temporary session now? This will sign out and wipe local memories, cache, and tokens from this phone.",
  temporaryExitDone: "Temporary session ended. Local data has been wiped.",
  temporaryExitFailed: "Could not complete secure wipe. Please retry.",
  accountSectionTitle: "Account",
  accountLocalLine: "Memories stay on this device unless you enable optional cloud backup.",
  accountCloudSignedIn: "Signed in for optional cloud backup.",
  accountCloudOff: "Not signed in for cloud backup.",
  subscriptionSectionTitle: "Subscription",
  subscriptionBody:
    "Free: local storage only. Plus: local plus optional cloud sync for your private pair. If you cancel Plus, download cloud data within 30 days — cloud copies are then removed automatically. Manage billing from your device’s subscription settings when available.",
  subscriptionManageCta: "Manage subscription",
  ringsSectionTitle: "Rings",
  ringsBody: "See up to two linked rings, invite your partner, or retire your own ring if it is lost.",
  ringsManageCta: "Manage rings",
  dataPrivacySectionTitle: "Data & privacy",
  legalSectionTitle: "Legal",
  termsLink: "Terms of Service",
  privacyContactLabel: "Privacy contact",
};

export const SETTINGS_CONTENT = {
  en: EN,
  fr: {
    ...EN,
    brand: "Réglages",
    title: "Contrôles axés confidentialité",
    back: "Retour",
    localSectionTitle: "Données locales",
    localDefault:
      "Par défaut : tout reste sur votre appareil. La sauvegarde cloud est optionnelle.",
    cloudSectionTitle: "Sauvegarde cloud optionnelle",
    privacySectionTitle: "Confidentialité",
    privacyPolicy: "Voir la politique de confidentialité",
    openHelp: "Ouvrir le centre d'aide",
  },
  es: {
    ...EN,
    brand: "Configuración",
    title: "Controles centrados en privacidad",
    back: "Volver",
    localSectionTitle: "Datos locales",
    localDefault:
      "Predeterminado: todo permanece en tu dispositivo. La copia en la nube es opcional.",
    cloudSectionTitle: "Copia en la nube opcional",
    privacySectionTitle: "Privacidad",
    privacyPolicy: "Ver política de privacidad",
    openHelp: "Abrir centro de ayuda",
  },
  de: {
    ...EN,
    brand: "Einstellungen",
    title: "Datenschutz zuerst",
    back: "Zurück",
    localSectionTitle: "Lokale Daten",
    localDefault: "Standard: Alles bleibt auf deinem Gerät. Cloud-Backup ist optional.",
    cloudSectionTitle: "Optionales Cloud-Backup",
    privacySectionTitle: "Datenschutz",
    privacyPolicy: "Datenschutzrichtlinie ansehen",
    openHelp: "Hilfecenter öffnen",
  },
  it: {
    ...EN,
    brand: "Impostazioni",
    title: "Controlli privacy-first",
    back: "Indietro",
    localSectionTitle: "Dati locali",
    localDefault:
      "Predefinito: tutto resta sul tuo dispositivo. Il backup cloud è opzionale.",
    cloudSectionTitle: "Backup cloud opzionale",
    privacySectionTitle: "Privacy",
    privacyPolicy: "Visualizza informativa privacy",
    openHelp: "Apri centro assistenza",
  },
};
