const EN = {
  brand: "Settings",
  title: "Privacy-first controls",
  back: "Back",
  localSectionTitle: "Local data",
  localDefault:
    "Default: Everything stays on your device. Cloud backup is optional.",
  loadingStats: "Loading local stats...",
  storageUnavailable: "Unavailable",
  storedStatsLabel: "Stored memories",
  estimatedStorageLabel: "Estimated storage",
  exportBackup: "Export Backup",
  clearAll: "Clear All Memories",
  deviceSecuritySectionTitle: "Trusted devices",
  deviceSecurityEnabled:
    "This Haven is protected by a password on new devices. Trusted devices can open with ring tap only.",
  deviceSecurityNotEnabled:
    "Device protection is not initialized yet. Complete setup from ring quick access flow.",
  deviceTrustedAtLabel: "Trusted on",
  revokeDevice: "Revoke",
  confirmRevokeDevice:
    "Remove this device trust? It will require password or recovery code next time.",
  deviceRevoked: "Device access revoked.",
  cloudSectionTitle: "Optional cloud backup",
  cloudToggleLabel:
    "Enable Cloud Backup (Sign in with Apple, can be turned off anytime)",
  cloudOff: "Cloud backup is off.",
  cloudEnabledNoSignIn: "Cloud backup is enabled but not signed in yet.",
  cloudEnabledSignedIn: "Cloud backup is enabled and linked.",
  signInApple: "Sign in with Apple",
  backupNow: "Backup Now",
  restore: "Restore",
  unlink: "Unlink Account",
  privacySectionTitle: "Privacy",
  privacyLine1: "All memories are stored locally on your device with encryption.",
  privacyLine2: "Cloud backup is completely optional.",
  privacyNfcLine:
    "NFC bind/unbind: we store only a secure fingerprint of the tag, not a naked UID. You can revoke a lost ring from another signed-in device.",
  privacyUnbindLine:
    "Unlinking a ring does not delete your sealed memories; it stops that ring from being used for quick access.",
  privacyLegacyLine:
    "Digital legacy options (if we offer them) require your explicit choice and are described in the privacy policy.",
  privacyE2eLine:
    "Your sealed memories are protected with end-to-end encryption on supported flows. Rings are shortcuts to your account, not the only proof of identity.",
  privacyPolicy: "View Privacy Policy",
  openHelp: "Open Help Center",
  confirmExport: "Export encrypted local backup file now?",
  preparingExport: "Preparing backup export...",
  exportDone: "Backup exported.",
  exportFailed: "Export failed.",
  confirmClear: "Delete all local memories from this device? This cannot be undone.",
  clearing: "Clearing local memories...",
  clearDone: "All local memories cleared.",
  clearFailed: "Could not clear memories.",
  confirmEnableCloud:
    "Enable optional cloud backup? Local-only mode remains available.",
  confirmDisableCloud:
    "Disable cloud backup? Existing local data will remain on this device.",
  cloudEnabledStatus: "Cloud backup enabled.",
  cloudDisabledStatus: "Cloud backup disabled.",
  confirmSignInApple: "Sign in with Apple for optional cloud backup now?",
  signingIn: "Linking Apple sign-in...",
  signInDone: "Apple backup account linked.",
  signInFailed: "Could not complete Apple sign-in.",
  confirmBackup: "Run cloud backup now? This uploads your encrypted local snapshot.",
  backingUp: "Running cloud backup...",
  backupDone: "Cloud backup completed.",
  backupFailed: "Cloud backup failed.",
  confirmRestore:
    "Restore from cloud backup now? This action may overwrite local expectations.",
  restoring: "Checking cloud backup...",
  restoreDone: "Cloud restore completed.",
  restoreFailed: "Cloud restore failed.",
  confirmUnlink: "Unlink cloud backup account from this device?",
  unlinkDone: "Cloud backup account unlinked.",
  loadStatsFailed: "Could not load local storage stats.",
  sessionSectionTitle: "Ring & session",
  keepSignedInLabel:
    "Stay signed in after NFC login (uses a longer server session until you sign out or revoke rings).",
  revokeAllNfcTitle: "Cloud-linked NFC rings",
  revokeAllNfcBody:
    "Revoke every ring binding for your account. Lost rings stop working immediately; sign in from Settings if needed.",
  revokeAllNfcButton: "Revoke all rings on this account",
  confirmRevokeAllNfc:
    "Revoke ALL NFC ring bindings for your cloud account? This cannot be undone from the ring side.",
  revokeAllNfcNeedSignIn: "Sign in with cloud backup first, then try again.",
  revokeAllNfcDone: "Revoked {n} ring binding(s). Cloud login may be required to add rings again.",
  revokeAllNfcFailed: "Could not revoke all rings.",
};

export const SETTINGS_CONTENT = {
  en: EN,
  fr: {
    ...EN,
    brand: "Réglages",
    title: "Contrôles axés confidentialité",
    back: "Retour",
    localSectionTitle: "Données locales",
    localDefault:
      "Par défaut : tout reste sur votre appareil. La sauvegarde cloud est optionnelle.",
    cloudSectionTitle: "Sauvegarde cloud optionnelle",
    privacySectionTitle: "Confidentialité",
    privacyPolicy: "Voir la politique de confidentialité",
    openHelp: "Ouvrir le centre d'aide",
  },
  es: {
    ...EN,
    brand: "Configuración",
    title: "Controles centrados en privacidad",
    back: "Volver",
    localSectionTitle: "Datos locales",
    localDefault:
      "Predeterminado: todo permanece en tu dispositivo. La copia en la nube es opcional.",
    cloudSectionTitle: "Copia en la nube opcional",
    privacySectionTitle: "Privacidad",
    privacyPolicy: "Ver política de privacidad",
    openHelp: "Abrir centro de ayuda",
  },
  de: {
    ...EN,
    brand: "Einstellungen",
    title: "Datenschutz zuerst",
    back: "Zurück",
    localSectionTitle: "Lokale Daten",
    localDefault: "Standard: Alles bleibt auf deinem Gerät. Cloud-Backup ist optional.",
    cloudSectionTitle: "Optionales Cloud-Backup",
    privacySectionTitle: "Datenschutz",
    privacyPolicy: "Datenschutzrichtlinie ansehen",
    openHelp: "Hilfecenter öffnen",
  },
  it: {
    ...EN,
    brand: "Impostazioni",
    title: "Controlli privacy-first",
    back: "Indietro",
    localSectionTitle: "Dati locali",
    localDefault:
      "Predefinito: tutto resta sul tuo dispositivo. Il backup cloud è opzionale.",
    cloudSectionTitle: "Backup cloud opzionale",
    privacySectionTitle: "Privacy",
    privacyPolicy: "Visualizza informativa privacy",
    openHelp: "Apri centro assistenza",
  },
};
