const EN = {
  brand: "Haven Timeline",
  title: "Your memories",
  tagline: "A quiet, sacred space — photo moments and stories you chose to seal.",
  back: "Back",
  create: "Create New Memory",
  settings: "Settings",
  offlineTip: "You are offline. Your encrypted timeline is still available locally.",
  loading: "Loading timeline...",
  empty: "No memories yet. Start by creating your first memory.",
  pin: "Pin",
  unpin: "Unpin",
  open: "Open",
  untitled: "Untitled memory",
  noStory: "No story text.",
  pinnedPrefix: "📌 ",
  pinnedNotice: "Memory pinned to top.",
  unpinnedNotice: "Pinned memory removed.",
  fabSealNew: "Seal new memory",
  welcomeBackNamed: "Welcome back, {name}",
  welcomeBack: "Welcome back",
  nfcRegionLabel: "Ring sign-in",
  nfcLede:
    "Any bound ring can quickly open this account. We recommend preparing at least two rings for backup, and your precious memories remain permanently safe in cloud storage with end-to-end encryption.",
  nfcCta: "Continue with ring",
  nfcScanning: "Hold your ring near the device…",
  nfcErrGeneric: "Could not sign in with this ring.",
  nfcErrNoBinding: "This ring is not linked to an account yet.",
  nfcErrNoUid: "Could not read the ring ID from the tag.",
  nfcErrUnconfigured: "Ring sign-in is not configured on this server.",
  cloudSourceNote:
    "Cloud remains the source of truth. Local ring caches are offline helpers and may be cleared by iOS.",
  integrityMismatch:
    "Detected data inconsistency. Cloud is the source of truth, please resync now.",
  resyncNow: "Resync",
  resyncing: "Resyncing…",
  cloudSectionTitle: "Cloud entries pending local reconciliation",
  cloudPlaceholderBody:
    "This item exists in cloud metadata for {ring}. Open/restore after sync to reconcile encrypted payload locally.",
  resyncActive: "Sync active ring",
  resyncAll: "Sync all rings",
  cloudGroupCount: "{n} cloud entries",
  cloudShowMore: "Show more",
  cloudShowLess: "Show less",
  syncIssueAuth: "Authentication expired. Sign in again to continue syncing.",
  syncIssueNetwork: "Network issue during sync. Please retry when connection is stable.",
  syncIssueHash:
    "Some entries failed integrity checks (hash mismatch). Keep cloud as source and resync.",
  syncStatusLabel: "Sync status",
  syncStatusRunning: "Running…",
  syncStatusIdle: "Idle",
  syncLastAttempt: "Last attempt: {time}",
  syncLastSuccess: "Last success: {time}",
  syncLastFailure: "Last failure: {reason}",
  syncFailureStreak: "Consecutive failures: {n}",
  syncNextRetry: "Next auto retry: {time}",
  rebuildLocalCache: "Rebuild local cache from cloud",
  syncLastRecovery: "Last cache rebuild: {time} ({count} rings)",
};

export const TIMELINE_PAGE_CONTENT = {
  en: EN,
  fr: {
    ...EN,
    title: "Vos souvenirs",
    tagline: "Un lieu calme pour ce qui compte — moments et histoires scelles.",
    back: "Retour",
    create: "Creer un souvenir",
    settings: "Reglages",
    offlineTip: "Vous etes hors ligne. Votre timeline chiffree reste disponible en local.",
    loading: "Chargement de la timeline...",
    empty: "Aucun souvenir pour le moment. Creez votre premier souvenir.",
    pin: "Epingler",
    unpin: "Retirer l'epingle",
    open: "Ouvrir",
    untitled: "Souvenir sans titre",
    noStory: "Pas de texte pour ce souvenir.",
    pinnedNotice: "Souvenir epingle en haut.",
    unpinnedNotice: "Epinglage retire.",
    fabSealNew: "Sceller un souvenir",
    welcomeBackNamed: "Bon retour, {name}",
    welcomeBack: "Bon retour",
  },
  es: {
    ...EN,
    title: "Tus recuerdos",
    tagline: "Un espacio sereno — momentos e historias que sellaste.",
    back: "Volver",
    create: "Crear nuevo recuerdo",
    settings: "Configuracion",
    offlineTip: "Estas sin conexion. Tu timeline cifrada sigue disponible en local.",
    loading: "Cargando timeline...",
    empty: "Aun no hay recuerdos. Empieza creando tu primer recuerdo.",
    pin: "Fijar",
    unpin: "Quitar fijado",
    open: "Abrir",
    untitled: "Recuerdo sin titulo",
    noStory: "Sin texto de historia.",
    pinnedNotice: "Recuerdo fijado arriba.",
    unpinnedNotice: "Fijado eliminado.",
    fabSealNew: "Sellar nuevo recuerdo",
    welcomeBackNamed: "Bienvenido de nuevo, {name}",
    welcomeBack: "Bienvenido de nuevo",
  },
  de: {
    ...EN,
    title: "Deine Erinnerungen",
    tagline: "Ein ruhiger Raum — Momente und Geschichten, die du versiegelt hast.",
    back: "Zuruck",
    create: "Neue Erinnerung",
    settings: "Einstellungen",
    offlineTip: "Du bist offline. Deine verschlusselte Timeline ist lokal verfugbar.",
    loading: "Timeline wird geladen...",
    empty: "Noch keine Erinnerungen. Erstelle deine erste Erinnerung.",
    pin: "Anheften",
    unpin: "Losen",
    open: "Offnen",
    untitled: "Unbenannte Erinnerung",
    noStory: "Kein Story-Text.",
    pinnedNotice: "Erinnerung oben angeheftet.",
    unpinnedNotice: "Anheften entfernt.",
    fabSealNew: "Neue Erinnerung versiegeln",
    welcomeBackNamed: "Willkommen zuruck, {name}",
    welcomeBack: "Willkommen zuruck",
  },
  it: {
    ...EN,
    title: "I tuoi ricordi",
    tagline: "Uno spazio quieto — momenti e storie che hai sigillato.",
    back: "Indietro",
    create: "Crea nuovo ricordo",
    settings: "Impostazioni",
    offlineTip: "Sei offline. La tua timeline cifrata resta disponibile in locale.",
    loading: "Caricamento timeline...",
    empty: "Nessun ricordo ancora. Inizia creando il primo.",
    pin: "Fissa",
    unpin: "Rimuovi fissato",
    open: "Apri",
    untitled: "Ricordo senza titolo",
    noStory: "Nessun testo storia.",
    pinnedNotice: "Ricordo fissato in alto.",
    unpinnedNotice: "Fissaggio rimosso.",
    fabSealNew: "Sigilla nuovo ricordo",
    welcomeBackNamed: "Bentornato, {name}",
    welcomeBack: "Bentornato",
  },
};
