const EN = {
  brand: "Haven Timeline",
  title: "Revisit your moments",
  back: "Back",
  create: "Create New Memory",
  settings: "Settings",
  offlineTip: "You are offline. Your encrypted timeline is still available locally.",
  loading: "Loading timeline...",
  empty: "No memories yet. Start by creating your first memory.",
  pin: "Pin",
  unpin: "Unpin",
  open: "Open",
  untitled: "Untitled memory",
  noStory: "No story text.",
  pinnedPrefix: "📌 ",
  pinnedNotice: "Memory pinned to top.",
  unpinnedNotice: "Pinned memory removed.",
};

export const TIMELINE_PAGE_CONTENT = {
  en: EN,
  fr: {
    ...EN,
    title: "Revoir vos souvenirs",
    back: "Retour",
    create: "Creer un souvenir",
    settings: "Reglages",
    offlineTip: "Vous etes hors ligne. Votre timeline chiffree reste disponible en local.",
    loading: "Chargement de la timeline...",
    empty: "Aucun souvenir pour le moment. Creez votre premier souvenir.",
    pin: "Epingler",
    unpin: "Retirer l'epingle",
    open: "Ouvrir",
    untitled: "Souvenir sans titre",
    noStory: "Pas de texte pour ce souvenir.",
    pinnedNotice: "Souvenir epingle en haut.",
    unpinnedNotice: "Epinglage retire.",
  },
  es: {
    ...EN,
    title: "Vuelve a tus recuerdos",
    back: "Volver",
    create: "Crear nuevo recuerdo",
    settings: "Configuracion",
    offlineTip: "Estas sin conexion. Tu timeline cifrada sigue disponible en local.",
    loading: "Cargando timeline...",
    empty: "Aun no hay recuerdos. Empieza creando tu primer recuerdo.",
    pin: "Fijar",
    unpin: "Quitar fijado",
    open: "Abrir",
    untitled: "Recuerdo sin titulo",
    noStory: "Sin texto de historia.",
    pinnedNotice: "Recuerdo fijado arriba.",
    unpinnedNotice: "Fijado eliminado.",
  },
  de: {
    ...EN,
    title: "Deine Momente erneut ansehen",
    back: "Zuruck",
    create: "Neue Erinnerung",
    settings: "Einstellungen",
    offlineTip: "Du bist offline. Deine verschlusselte Timeline ist lokal verfugbar.",
    loading: "Timeline wird geladen...",
    empty: "Noch keine Erinnerungen. Erstelle deine erste Erinnerung.",
    pin: "Anheften",
    unpin: "Losen",
    open: "Offnen",
    untitled: "Unbenannte Erinnerung",
    noStory: "Kein Story-Text.",
    pinnedNotice: "Erinnerung oben angeheftet.",
    unpinnedNotice: "Anheften entfernt.",
  },
  it: {
    ...EN,
    title: "Rivedi i tuoi ricordi",
    back: "Indietro",
    create: "Crea nuovo ricordo",
    settings: "Impostazioni",
    offlineTip: "Sei offline. La tua timeline cifrata resta disponibile in locale.",
    loading: "Caricamento timeline...",
    empty: "Nessun ricordo ancora. Inizia creando il primo.",
    pin: "Fissa",
    unpin: "Rimuovi fissato",
    open: "Apri",
    untitled: "Ricordo senza titolo",
    noStory: "Nessun testo storia.",
    pinnedNotice: "Ricordo fissato in alto.",
    unpinnedNotice: "Fissaggio rimosso.",
  },
};
